const crypto=require('node:crypto'),zlib=require('node:zlib');
const {roomNumber,normalizeBiliEvent}=require('./live-interactions.cjs');
const MAX_PACKET=4*1024*1024;
function packet(op,body='',version=1){const bytes=Buffer.isBuffer(body)?body:Buffer.from(body),header=Buffer.alloc(16);header.writeUInt32BE(16+bytes.length);header.writeUInt16BE(16,4);header.writeUInt16BE(version,6);header.writeUInt32BE(op,8);header.writeUInt32BE(1,12);return Buffer.concat([header,bytes]);}
function decode(bytes,depth=0,budget={left:8*1024*1024}){const b=Buffer.from(bytes);if(depth>4||b.length>MAX_PACKET||b.length>budget.left)throw Error('直播消息包超出大小限制');budget.left-=b.length;const result=[];let offset=0;
 while(offset<b.length){if(b.length-offset<16)throw Error('直播消息包不完整');const size=b.readUInt32BE(offset),head=b.readUInt16BE(offset+4),version=b.readUInt16BE(offset+6),op=b.readUInt32BE(offset+8);if(head<16||size<head||size>MAX_PACKET||offset+size>b.length)throw Error('直播消息包格式不正确');const body=b.subarray(offset+head,offset+size);offset+=size;
  if(version===2||version===3){const inflated=version===2?zlib.inflateSync(body,{maxOutputLength:MAX_PACKET}):zlib.brotliDecompressSync(body,{maxOutputLength:MAX_PACKET});result.push(...decode(inflated,depth+1,budget));}
  else if(version===0||version===1){if(op===5||op===8){result.push({op,data:body.length?JSON.parse(body.toString('utf8').replace(/\0+$/,'')):{code:0}});}else result.push({op});}
  else throw Error('暂不支持此直播消息协议');
 }return result;
}
function signedHeaders(body,keyId,secret,{now=Date.now,nonce=crypto.randomUUID}={}){const headers={'x-bili-accesskeyid':keyId,'x-bili-content-md5':crypto.createHash('md5').update(body).digest('hex'),'x-bili-signature-method':'HMAC-SHA256','x-bili-signature-nonce':nonce(),'x-bili-signature-version':'1.0','x-bili-timestamp':String(Math.floor(now()/1000))};const message=Object.keys(headers).sort().map(k=>k+':'+headers[k]).join('\n');return{...headers,Authorization:crypto.createHmac('sha256',secret).update(message).digest('hex'),'Content-Type':'application/json',Accept:'application/json'};}
function credentials(input){if(!input||typeof input!=='object')throw Error('请填写官方接入信息');const c={};for(const k of ['appId','accessKeyId','accessKeySecret','code']){if(typeof input[k]!=='string'||!input[k].trim()||input[k].length>200||/[\r\n\0]/.test(input[k]))throw Error('请完整填写官方接入信息');c[k]=input[k].trim();}if(!/^[1-9]\d{0,18}$/.test(c.appId))throw Error('应用ID需为正整数');return c;}
function safeWss(value){const u=new URL(value);if(u.protocol!=='wss:'||u.username||u.password||!(u.hostname==='broadcastlv.chat.bilibili.com'||u.hostname.endsWith('.chat.bilibili.com')||u.hostname.endsWith('.biliapi.net')||u.hostname.endsWith('.bilibili.com')))throw Error('B站返回的长连地址不正确');return u.href;}
function createBilibiliClient({fetchImpl=fetch,WebSocketImpl=globalThis.WebSocket,now=Date.now,setIntervalImpl=setInterval,clearIntervalImpl=clearInterval,setTimeoutImpl=setTimeout,clearTimeoutImpl=clearTimeout,onEvent=()=>{},onRoom=()=>{},onUpdate=()=>{}}={}){
 let epoch=0,desired=false,mode='public',roomId='',anchor='',status='disconnected',message='尚未连接B站直播间',socket=null,authBody='',wssLinks=[],gameId='',keys=null,controller=null,heartbeat=null,appHeartbeat=null,reconnect=null,authTimeout=null,retry=0,lastHeartbeat=0,lastEventAt=null,appHeartbeatBusy=false;
 const snapshot=()=>({status,message,mode,roomId,anchor,lastEventAt,credentialsLoaded:!!keys});
 const update=(s,m)=>{status=s;message=m;onUpdate(snapshot());};
 function stopTimers(){for(const t of [heartbeat,appHeartbeat])if(t)clearIntervalImpl(t);for(const t of [reconnect,authTimeout])if(t)clearTimeoutImpl(t);heartbeat=appHeartbeat=reconnect=authTimeout=null;}
 async function getJSON(url,options={},signal=controller?.signal){let response;try{response=await fetchImpl(url,{...options,signal:signal?AbortSignal.any([signal,AbortSignal.timeout(10000)]):AbortSignal.timeout(10000)});}catch{throw Error('无法访问B站接口，请检查网络后重试');}if(!response.ok)throw Error('B站接口暂不可用（HTTP '+response.status+'）');let data;try{data=await response.json();}catch{throw Error('B站接口返回了无效数据');}if(data.code!==0)throw Error('B站接口拒绝访问（'+data.code+'），请检查接入信息或改用官方接入');return data.data;}
 async function official(path,data,key=keys,signal){const body=JSON.stringify(data).replace(/"app_id":"([1-9]\d{0,18})"/,'"app_id":$1');return getJSON('https://live-open.biliapi.com/v2/app/'+path,{method:'POST',body,headers:signedHeaders(body,key.accessKeyId,key.accessKeySecret,{now})},signal);}
 async function endSession(id,oldKeys){if(!id||!oldKeys)return;try{await official('end',{app_id:oldKeys.appId,game_id:id},oldKeys,null);}catch{}}
 async function disconnect(){desired=false;epoch++;controller?.abort();controller=null;stopTimers();const oldGame=gameId,oldKeys=keys;gameId='';authBody='';wssLinks=[];keys=null;const old=socket;socket=null;try{old?.close();}catch{}update('disconnected','已断开B站直播间');await endSession(oldGame,oldKeys);}
 function fail(e,myEpoch){if(myEpoch!==epoch)return;desired=false;controller?.abort();controller=null;stopTimers();const old=socket;socket=null;try{old?.close();}catch{}const id=gameId,k=keys;gameId='';keys=null;void endSession(id,k);update('error',e.message||'B站连接失败，请重试');}
 function schedule(myEpoch){if(!desired||myEpoch!==epoch||reconnect)return;update('reconnecting','弹幕连接中断，正在重连；断线期间的事件可能未收到');const delay=Math.min(30000,1000*2**Math.min(retry++,5));reconnect=setTimeoutImpl(()=>{reconnect=null;openSocket(myEpoch);},delay);reconnect.unref?.();}
 function openSocket(myEpoch){if(!desired||myEpoch!==epoch)return;let ws;try{ws=new WebSocketImpl(safeWss(wssLinks[retry%wssLinks.length]));}catch(e){fail(e,myEpoch);return;}socket=ws;ws.binaryType='arraybuffer';update('authenticating','已连接消息服务器，等待B站鉴权');
  authTimeout=setTimeoutImpl(()=>{if(socket===ws&&status!=='connected'){try{ws.close();}catch{}schedule(myEpoch);}},15000);authTimeout.unref?.();
  ws.addEventListener('open',()=>{if(myEpoch!==epoch||socket!==ws)return;try{ws.send(packet(7,authBody));}catch{schedule(myEpoch);}});
  ws.addEventListener('message',async event=>{if(myEpoch!==epoch||socket!==ws)return;try{const bytes=event.data instanceof Blob?await event.data.arrayBuffer():event.data;if(myEpoch!==epoch||socket!==ws)return;for(const item of decode(bytes)){
    if(item.op===8){if(item.data.code!==0){fail(Error('B站鉴权失败，请重新连接或检查身份码'),myEpoch);return;}if(authTimeout)clearTimeoutImpl(authTimeout);authTimeout=null;retry=0;lastHeartbeat=now();update('connected','B站直播间已连接 · '+roomId);if(heartbeat)clearIntervalImpl(heartbeat);ws.send(packet(2));heartbeat=setIntervalImpl(()=>{if(socket!==ws||myEpoch!==epoch)return;try{if(now()-lastHeartbeat>75000){ws.close();schedule(myEpoch);return;}ws.send(packet(2));}catch{schedule(myEpoch);}},30000);heartbeat.unref?.();}
    else if(item.op===3)lastHeartbeat=now();
    else if(item.op===5&&status==='connected'){const e=normalizeBiliEvent(item.data,{roomId,now});if(e){lastEventAt=now();onEvent(e);}}
  }}catch(e){fail(Error('直播消息解析失败，请重新连接'),myEpoch);}});
  const lost=()=>{if(socket!==ws||myEpoch!==epoch)return;socket=null;if(heartbeat)clearIntervalImpl(heartbeat);if(authTimeout)clearTimeoutImpl(authTimeout);heartbeat=authTimeout=null;schedule(myEpoch);};ws.addEventListener('close',lost);ws.addEventListener('error',()=>{try{ws.close();}catch{}lost();});
 }
 async function connect(input){const chosenMode=input.mode||'public',requestedRoom=roomNumber(input.roomId),newKeys=chosenMode==='official'?credentials(input.credentials):null;if(!['public','official'].includes(chosenMode))throw Error('接入方式不正确');if(typeof WebSocketImpl!=='function')throw Error('当前运行环境不支持直播长连，请使用附带的运行环境');if(chosenMode==='public'&&!requestedRoom)throw Error('先填写B站直播间房间号');await disconnect();desired=true;mode=chosenMode;keys=newKeys;roomId=requestedRoom;anchor='';lastEventAt=null;retry=0;controller=new AbortController();const myEpoch=epoch;update('connecting','正在连接B站直播间…');
  try{
   if(mode==='official'){const data=await official('start',{app_id:keys.appId,code:keys.code});if(myEpoch!==epoch){await endSession(data?.game_info?.game_id,newKeys);return snapshot();}gameId=data?.game_info?.game_id;roomId=String(data?.anchor_info?.room_id||'');anchor=String(data?.anchor_info?.uname||'').slice(0,100);authBody=data?.websocket_info?.auth_body;wssLinks=data?.websocket_info?.wss_link;if(!gameId||!authBody||!Array.isArray(wssLinks)||!wssLinks.length||!roomId)throw Error('官方接入返回缺少连接信息');if(requestedRoom&&requestedRoom!==roomId){const init=await getJSON('https://api.live.bilibili.com/room/v1/Room/room_init?id='+requestedRoom);if(myEpoch!==epoch)return snapshot();if(String(init.room_id)!==roomId)throw Error('身份码所属直播间与填写的房间不一致，请检查身份码');}onRoom(roomNumber(roomId));appHeartbeat=setIntervalImpl(async()=>{if(myEpoch!==epoch||!desired||appHeartbeatBusy)return;appHeartbeatBusy=true;try{await official('heartbeat',{game_id:gameId});}catch(e){fail(Error('官方会话心跳失败，请重新连接'),myEpoch);}finally{appHeartbeatBusy=false;}},20000);appHeartbeat.unref?.();}
   else{const init=await getJSON('https://api.live.bilibili.com/room/v1/Room/room_init?id='+requestedRoom,{headers:{'User-Agent':'Mozilla/5.0','Referer':'https://live.bilibili.com/'+requestedRoom}});if(myEpoch!==epoch)return snapshot();roomId=String(init.room_id);onRoom(roomNumber(roomId));const data=await getJSON('https://api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo?id='+roomId+'&type=0',{headers:{'User-Agent':'Mozilla/5.0','Referer':'https://live.bilibili.com/'+roomId}});if(myEpoch!==epoch)return snapshot();if(!data?.token||!Array.isArray(data.host_list)||!data.host_list.length)throw Error('B站没有返回弹幕连接信息，请改用官方接入');wssLinks=data.host_list.map(h=>'wss://'+h.host+':'+(h.wss_port||443)+'/sub');authBody=JSON.stringify({uid:0,roomid:Number(roomId),protover:3,platform:'web',type:2,key:data.token});}
   wssLinks=wssLinks.map(safeWss);if(typeof authBody!=='string'||authBody.length>20000)throw Error('B站鉴权数据格式不正确');if(myEpoch===epoch)openSocket(myEpoch);
  }catch(e){fail(e,myEpoch);}return snapshot();
 }
 function close(){desired=false;epoch++;controller?.abort();stopTimers();try{socket?.close();}catch{}socket=null;const id=gameId,k=keys;gameId='';keys=null;void endSession(id,k);}
 return{snapshot,connect,disconnect,close};
}
module.exports={createBilibiliClient,packet,decode,signedHeaders,credentials,safeWss};
