const defaults={dailyEnabled:false,dailyWaiting:true,dailyGame:false,dailyBreak:true,dailyZerglings:true,dailyZealots:true,dailyWorkersKilled:true,dailyLongest:true,dailyStrongest:true,dailyRecord:false,dailyTime:false,dailyTitle:'今日小战报',dailyStyle:'compact',dailyFollowTheme:true,dailyAccent:'#83c5b6',dailyX:40,dailyY:160,dailyWidth:460,dailyScale:100,dailyOpacity:90};
const flags=Object.keys(defaults).filter(k=>typeof defaults[k]==='boolean');
function sanitize(input,base){const c={...base};for(const k of flags)if(k in input){if(typeof input[k]!=='boolean')throw Error('今日数据开关格式不正确');c[k]=input[k];}if('dailyTitle'in input){if(typeof input.dailyTitle!=='string'||[...input.dailyTitle].length>24||/[\r\n\0]/.test(input.dailyTitle))throw Error('今日数据标题最多24字');c.dailyTitle=input.dailyTitle.trim();}if('dailyStyle'in input){if(!['compact','tiles'].includes(input.dailyStyle))throw Error('今日数据样式不正确');c.dailyStyle=input.dailyStyle;}if('dailyAccent'in input){if(typeof input.dailyAccent!=='string'||!/^#[a-f\d]{6}$/i.test(input.dailyAccent))throw Error('今日数据颜色不正确');c.dailyAccent=input.dailyAccent;}for(const [k,min,max]of [['dailyX',0,1700],['dailyY',0,980],['dailyWidth',320,900],['dailyScale',50,150],['dailyOpacity',20,100]])if(k in input){if(!Number.isInteger(input[k])||input[k]<min||input[k]>max)throw Error('今日数据外观数值超出范围');c[k]=input[k];}return c;}
function metrics(input){if(!input||input.version!==1)return null;const out={version:1};for(const k of ['zerglings','zealots','workersKilled']){const v=input[k];if(v!==null&&(!Number.isSafeInteger(v)||v<0||v>10000000))return null;out[k]=v;}out.status=Object.values(out).slice(1).some(v=>v!==null)?'ready':'unavailable';out.note=typeof input.note==='string'?input.note.slice(0,180):'';return out;}
function enrich(record,parsed,opponent){let changed=false;const next=metrics(parsed.dailyMetrics);if(next){const merged={...next};for(const k of ['zerglings','zealots','workersKilled'])if(next[k]===null&&record.dailyMetrics?.[k]!=null)merged[k]=record.dailyMetrics[k];if(JSON.stringify(record.dailyMetrics)!==JSON.stringify(merged)){record.dailyMetrics=merged;changed=true;}}if(Number.isInteger(opponent?.mmr)&&opponent.mmr>0&&opponent.mmr<=20000&&record.opponentMMR!==opponent.mmr){record.opponentMMR=opponent.mmr;changed=true;}return changed;}
function summarize(counted){const replays=counted.filter(r=>r.replayKey),coverage={},issues=[];const sums={};for(const k of ['zerglings','zealots','workersKilled']){const parsed=replays.filter(r=>Number.isSafeInteger(r.dailyMetrics?.[k])&&r.dailyMetrics[k]>=0);coverage[k]=parsed.length;sums[k]=counted.length&&!parsed.length?null:parsed.reduce((s,r)=>s+r.dailyMetrics[k],0);}
 for(const r of replays){const keys=['zerglings','zealots','workersKilled'].filter(k=>!Number.isSafeInteger(r.dailyMetrics?.[k])||r.dailyMetrics[k]<0);if(!keys.length)continue;const note=r.dailyMetrics?.note||'旧记录尚未解析单位数据，请扫描今日录像';const existing=issues.find(x=>x.note===note&&x.keys.join(',')===keys.join(','));if(existing)existing.count++;else issues.push({keys,note,count:1});}
 const strongest=replays.filter(r=>r.matchType!=='ai1v1'&&Number.isInteger(r.opponentMMR)&&r.opponentMMR>0&&r.opponentMMR<=20000).reduce((b,r)=>!b||r.opponentMMR>b.opponentMMR||r.opponentMMR===b.opponentMMR&&r.at>b.at?r:b,null);return{...sums,coverage,issues,replayCount:replays.length,manualCount:counted.length-replays.length,mmrCount:replays.filter(r=>r.matchType!=='ai1v1'&&Number.isInteger(r.opponentMMR)&&r.opponentMMR>0&&r.opponentMMR<=20000).length,seconds:replays.filter(r=>Number.isFinite(r.durationSeconds)&&r.durationSeconds>0).reduce((s,r)=>s+r.durationSeconds,0),timeCount:replays.filter(r=>Number.isFinite(r.durationSeconds)&&r.durationSeconds>0).length,strongest:strongest?{id:strongest.id,name:strongest.opponent,mmr:strongest.opponentMMR,race:strongest.opponentRace,map:strongest.map||'',result:strongest.result,at:strongest.at}:null};}
module.exports={defaults,sanitize,metrics,enrich,summarize};
