const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const {createReplayStore,sanitize}=require('../ladder-replays.cjs'),{createReplayWatcher}=require('../replay-watcher.cjs'),{createAssistant}=require('../ladder-server.cjs');
const at=Date.parse('2026-10-07T08:00:00Z');
function replay(time=at+10000,ai=true){const me={human:true,toonHandle:'5-S2-1-9',name:'Me',mmr:6000,race:'Protoss'},op={human:!ai,toonHandle:ai?'0-S2-0-0':'5-S2-1-8',name:ai?'Computer':'Opponent',mmr:7000,race:'Zerg'};return{ok:true,at:time,durationSeconds:300,map:'Map',players:[me,op],selfPlayers:[me],opponents:[op],selfResult:'W',dailyMetrics:{version:1,zerglings:0,zealots:24,workersKilled:15}};}
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'人机开关-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('AI is off by default; enabling accepts only own human versus one computer, never updates MMR',()=>{
 const s=createReplayStore(null,()=>at+20000);s.configure({toonHandle:'5-S2-1-9'});assert.equal(s.getConfig().includeAI,false);assert.equal(s.acceptReplay(replay(),'ai').kind,'skipped');s.updateMMR(4000);s.configure({includeAI:true,mmrMode:'estimate'});assert.equal(s.acceptReplay(replay(at+25000),'ai').kind,'recorded');assert.equal(s.snapshot().stats.wins,1);assert.equal(s.snapshot().session.stats.wins,1);assert.equal(s.getConfig().mmr,4000);assert.equal(s.getConfig().mmrSource,'manual');assert.equal(s.snapshot().records[0].matchType,'ai1v1');assert.equal(s.snapshot().stats.daily.zealots,24);assert.equal(s.snapshot().stats.daily.strongest,null);assert.equal(s.snapshot().stats.daily.mmrCount,0);
 for(const value of ['true',1,null])assert.throws(()=>sanitize({includeAI:value}));
 for(const change of [p=>p.selfPlayers=[],p=>p.selfPlayers.push({...p.selfPlayers[0]}),p=>p.players.push({human:false}),p=>p.selfPlayers[0].human=false,p=>delete p.players[1].human,p=>p.selfResult=null]){const p=replay();change(p);assert.equal(s.acceptReplay(p,'invalid').kind,'skipped');}
});
test('AI toggle filters daily and session statistics reversibly, preserves exclusions and deduplicates rescans/restarts',t=>{
 let clock=at;const file=path.join(temp(t),'records.json'),s=createReplayStore(file,()=>clock);s.configure({toonHandle:'5-S2-1-9',includeAI:true});clock+=10000;const ai=replay(clock);s.acceptReplay(ai,'ai');clock+=10000;s.acceptReplay(replay(clock,false),'human');assert.equal(s.snapshot().session.stats.total,2);s.configure({includeAI:false});assert.equal(s.snapshot().session.stats.total,1);assert.equal(s.snapshot().stats.daily.zealots,24);assert.equal(s.snapshot().records.length,2);s.configure({includeAI:true});assert.equal(s.acceptReplay(ai,'copy').kind,'duplicate');assert.equal(s.snapshot().stats.total,2);s.edit(s.snapshot().records.find(r=>r.matchType==='ai1v1').id,{excluded:true});s.configure({includeAI:false});s.configure({includeAI:true});assert.equal(s.snapshot().stats.total,1);const restored=createReplayStore(file,()=>clock+10000);assert.equal(restored.getConfig().includeAI,true);assert.equal(restored.snapshot().stats.total,1);assert.equal(restored.snapshot().session.stats.total,0);
});
test('undo selects the last counted human match while hidden AI history stays intact; manual AI links once',()=>{
 let clock=at;const s=createReplayStore(null,()=>clock);s.configure({toonHandle:'5-S2-1-9',includeAI:true});clock+=10000;s.acceptReplay(replay(clock,false),'human');clock+=10000;s.acceptReplay(replay(clock),'ai');s.configure({includeAI:false});s.undo('session');assert.equal(s.snapshot().session.stats.total,0);const ai=s.snapshot().records.find(r=>r.matchType==='ai1v1');assert.equal(ai.excluded,false);s.configure({includeAI:true});assert.equal(s.snapshot().session.stats.total,1);
 const other=createReplayStore(null,()=>clock);other.configure({toonHandle:'5-S2-1-9',includeAI:true});other.add('loss',{opponent:'Computer'});other.acceptReplay(replay(clock),'linked');assert.equal(other.snapshot().stats.total,1);assert.equal(other.snapshot().stats.losses,1);assert.equal(other.snapshot().records[0].matchType,'ai1v1');
});
test('watcher reconsiders cached AI skips after enabling, without duplicate records or requiring a new replay',async t=>{
 const dir=temp(t),file=path.join(dir,'Practice.SC2Replay');fs.writeFileSync(file,'ai');fs.utimesSync(file,new Date(at),new Date(at));const s=createReplayStore(null,()=>at+20000);s.configure({toonHandle:'5-S2-1-9',replayDirectory:dir});const w=createReplayWatcher({store:s,now:()=>at+20000,parser:async()=>replay(),intervalMs:100000});t.after(()=>w.close());await w.scan('auto');assert.equal(s.snapshot().stats.total,0);s.configure({includeAI:true});await w.scan('auto');assert.equal(s.snapshot().stats.total,1);await w.scan('today');assert.equal(s.snapshot().stats.total,1);
});
test('local control authenticates the persisted AI option and exposes its default-off checkbox',async t=>{
 const app=createAssistant({port:0,dataDir:temp(t),sc2Reader:async()=> 'offline',intervalMs:100000});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const base='http://127.0.0.1:'+app.server.address().port,html=await(await fetch(base)).text(),token=html.match(/name="control-token" content="([a-f\d]+)"/)[1];assert.match(html,/id="includeAI" type="checkbox">计入人机对局/);const send=(config,auth)=>fetch(base+'/api/action',{method:'POST',headers:auth?{'X-Control-Token':token}:{},body:JSON.stringify({action:'ladderConfigure',config})});assert.equal((await send({includeAI:true},false)).status,403);assert.equal((await send({includeAI:'true'},true)).status,400);assert.equal((await send({includeAI:true},true)).status,200);assert.equal(app.snapshot().ladder.config.includeAI,true);
});
