const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const {defaults,sanitize,createReplayStore}=require('../ladder-replays.cjs'),K=require('../public/cat-keyboard-template.js'),{filteredKeys}=require('../keyboard-input.cjs'),R=require('../public/resource-template.js'),P=require('../public/protoss-console.js'),F=require('../public/gameframe-template.js'),O=require('../public/outfit-presets.js'),{createAssistant}=require('../ladder-server.cjs');
test('rally uses a fresh custom key, stays while held, expires after release and clears with chat or lost focus',()=>{
 let at=0;const c={...defaults,catCharacter:'artanis',catRallyKey:'F7',catRallyHold:600,catFunctions:false},m=K.createModel({now:()=>at});const event=(sequence,pressed,status='active')=>m.ingest({sequence,pressed,status},c);
 event(1,['F2']);assert.equal(m.snapshot(c).rally,false);event(2,['F7']);assert.equal(m.snapshot(c).rally,true);assert.deepEqual(m.snapshot(c).pressed,[],'hidden categories still trigger but do not light or show key text');at=10000;assert.equal(m.snapshot(c).rally,true);event(3,[]);at=10599;assert.equal(m.snapshot(c).rally,true);at=10600;assert.equal(m.snapshot(c).rally,false);
 event(4,['F7']);event(5,[],'chat');assert.equal(m.snapshot(c).rally,false);event(6,['F7']);event(7,[],'waiting');assert.equal(m.snapshot(c).rally,false);
 event(8,['F7']);c.catRallyKey='F2';assert.equal(m.snapshot(c).rally,false);c.catRallyKey='F7';assert.equal(m.snapshot(c).rally,false,'changing a binding does not replay the currently held key');event(9,[]);event(10,['F7']);assert.equal(m.snapshot(c).rally,true);c.catView='flat';assert.equal(m.snapshot(c).rally,false);c.catView='rear';c.catCharacter='nahida';assert.equal(m.snapshot(c).rally,false);
});
test('custom trigger bypasses only its own display filter and remains unbound by default',()=>{
 assert.equal(defaults.catRallyKey,'');const c={...defaults,catCharacter:'artanis',catRallyKey:'F7',catFunctions:false};assert.deepEqual(filteredKeys(['F7','F2','Q','invalid'],c),['Q','F7']);assert.deepEqual(filteredKeys(['F7','Q'],{...c,catCharacter:'cat'}),['Q']);assert.deepEqual(filteredKeys(['F7','Q'],{...c,catRallyKey:''}),['Q']);
 for(const patch of [{catRallyKey:'evil'},{catRallyKey:7},{catRallyHold:0},{catRallyHold:3001},{gameFrameCoverage:'all'},{resourceBadgeMineral:'true'},{resourcePaimonSize:121}])assert.throws(()=>sanitize(patch));
 const html=K.build({...c,catView:'rear'});assert.match(html,/cat-character-artanis/);assert.match(html,/集结部队/);assert.equal((html.match(/class="cat-board"/g)||[]).length,1);assert.doesNotMatch(K.build({...c,catView:'flat'}),/cat-avatar|cat-rally-callout/);
});
test('assistant binding, coverage, menu badges and Paimon persist; outfits preserve user trigger and resource choices',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'artanis-menu-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'records.json'),store=createReplayStore(file);const patch={catCharacter:'artanis',catRallyKey:'Q',catRallyHold:1800,gameFrameCoverage:'safe',resourceStyle:'genshin-menu',resourcePaimonEnabled:true,resourceBadgeSupply:true,resourcePaimonBadge:true};store.configure(patch);const before=createReplayStore(file).snapshot().config;for(const [k,v]of Object.entries(patch))assert.equal(before[k],v);
 const outfit=O.buildPatch(before,{preset:'protoss'});assert.equal(outfit.catCharacter,'artanis');assert.equal(outfit.catRallyKey,undefined);assert.equal(outfit.resourceStyle,undefined);store.configure(outfit);assert.equal(store.snapshot().config.catRallyKey,'Q');assert.equal(store.snapshot().config.resourcePaimonEnabled,true);
 const combo=O.captureCombination(before);assert.equal(combo.gameFrameCoverage,'safe');assert.equal(combo.catRallyKey,undefined);
});
test('rich frames fill selection margins and replace portrait while retaining protected game windows',()=>{
 for(const style of ['artanis','zealot']){const c={...defaults,gameFrameStyle:style,gameFrameCoverage:'rich'},svg=F.build(c,{assets:{[style]:'data:image/png;base64,AA=='}});assert.match(svg,/data-panel="selection-fill"/);assert.match(svg,new RegExp('data-decoration="'+style+'-portrait"'));assert.match(svg,/data:image\/png;base64,AA==/);for(const a of P.protectedAreas(c))assert.ok(svg.includes('data-protected="'+a.name+'"'),a.name);assert.doesNotMatch(svg,/data-protected="unit-portrait"/);assert.equal(P.protectedAreas({...c,gameFrameCoverage:'safe'}),P.safeAreas);assert.doesNotMatch(F.build({...c,gameFrameSelection:false,gameFramePortrait:false}),/selection-fill|data-decoration=".*-portrait"/);assert.doesNotMatch(F.build({...c,gameFrameDecorations:false}),/data-decoration=|<image/);}
});
test('menu badges are independently toggled and Paimon can render with resource replacements off',()=>{
 const c={...R.defaults,resourceStyle:'genshin-menu'};assert.equal((R.build(c).match(/data-resource-slot=/g)||[]).length,3);assert.doesNotMatch(R.build(c),/data-resource-badge|data-resource-paimon/);for(const key of ['Mineral','Vespene','Supply'])assert.equal((R.build({...c,['resourceBadge'+key]:true}).match(/data-resource-badge=/g)||[]).length,1);
 const svg=R.build({...c,resourcePaimonEnabled:true,resourcePaimonBadge:true},{showResources:false});assert.match(svg,/paimon-menu-v1\.png/);assert.match(svg,/data-resource-badge/);assert.doesNotMatch(svg,/data-resource-slot=/);for(const p of R.numberAreas)assert.ok(svg.includes(`x="${p.x}" y="${p.y}" width="${p.w}" height="${p.h}" fill="black"`));
 const box={hidden:false,innerHTML:''},window={ResourceTemplate:R};vm.runInNewContext(fs.readFileSync(require.resolve('../public/resource-overlay.js'),'utf8'),{window,document:{getElementById:()=>box,body:{dataset:{}}}});window.ResourceOverlay.render({scene:'game',ladder:{config:{...defaults,resourceEnabled:false,resourcePaimonEnabled:true}}});assert.equal(box.hidden,false);assert.doesNotMatch(box.innerHTML,/data-resource-slot=/);window.ResourceOverlay.render({scene:'blank',ladder:{config:{...defaults,resourcePaimonEnabled:true}}});assert.equal(box.hidden,true);
});
test('all new assets have alpha and public routes, and exported rich console embeds character art',async t=>{
 const app=createAssistant({port:0,dataDir:null,sc2Reader:async()=>{throw Error('offline');},intervalMs:60000});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const root='http://127.0.0.1:'+app.server.address().port;
 for(const name of ['artanis-keys-v1.png','artanis-rally-v1.png','resource-genshin-menu-v1.png','paimon-menu-v1.png']){const bytes=fs.readFileSync(path.join(__dirname,'../public/assets',name));assert.equal(bytes[25],6,name);if(name.includes('keys')||name.includes('resource-'))assert.equal(bytes.readUInt32BE(16),3*bytes.readUInt32BE(20));assert.equal((await fetch(root+'/assets/'+name)).status,200);}
 app.ladder.configure({gameFrameStyle:'artanis',gameFrameCoverage:'rich'});const svg=await(await fetch(root+'/gameframe.svg')).text();assert.match(svg,/data:image\/png;base64,/);assert.doesNotMatch(svg,/href="\/assets/);const html=await(await fetch(root)).text();for(const id of ['catRallyKey','catRallyRecord','catRallyDemo','resourcePaimonEnabled','resourceBadgeMineral','gameFrameCoverage'])assert.ok(html.includes('id="'+id+'"'));assert.match(html,/\/cat-keyboard-template\.js/);
});
