const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm'),{spawnSync}=require('node:child_process');
const {createReplayStore,sanitize}=require('../ladder-replays.cjs'),{parseReplay}=require('../replay-watcher.cjs'),{createAssistant}=require('../ladder-server.cjs');
const AT=Date.parse('2026-10-06T08:00:00Z'),ME={toonHandle:'5-S2-1-1',name:'Me',human:true,race:'Zerg',mmr:5000},OP={toonHandle:'5-S2-1-2',name:'Other',human:true,race:'Protoss',mmr:5200};
const parsed=(at=AT,patch={})=>({ok:true,at,durationSeconds:1200,map:'Map',players:[ME,OP],selfPlayers:[ME],opponents:[OP],selfResult:'W',dailyMetrics:{version:1,zerglings:40,zealots:0,workersKilled:12,status:'ready',note:''},...patch});
test('Python tracker counts completed own production, credited worker kills and recycled tags without duplicate morphs',()=>{const r=spawnSync(require('../runtime-paths.cjs').python(),['-X','utf8',path.join(__dirname,'daily-parser-test.py')],{encoding:'utf8',windowsHide:true});assert.equal(r.status,0,r.stdout+r.stderr);assert.match(r.stderr,/Ran 3 tests/);});
test('daily stats aggregate only counted current-account Beijing-day replays and preserve exclusions, strongest and partial coverage',()=>{
 let clock=AT+60000;const s=createReplayStore(null,()=>clock);s.configure({toonHandle:ME.toonHandle});s.acceptReplay(parsed(),'one');s.acceptReplay(parsed(AT+1000,{opponents:[{...OP,name:'Strong',mmr:6000}],dailyMetrics:{version:1,zerglings:80,zealots:7,workersKilled:8},durationSeconds:1800}),'two');s.acceptReplay(parsed(AT-86400000),'old');s.acceptReplay(parsed(AT+2000,{dailyMetrics:null,opponents:[{...OP,mmr:null}]}),'missing');let d=s.snapshot().stats.daily;assert.equal(d.zerglings,120);assert.equal(d.zealots,7);assert.equal(d.workersKilled,20);assert.equal(d.coverage.zerglings,2);assert.equal(d.replayCount,3);assert.equal(d.strongest.name,'Strong');
 const strong=s.snapshot().records.find(r=>r.opponent==='Strong');s.edit(strong.id,{excluded:true});d=s.snapshot().stats.daily;assert.equal(d.zerglings,40);assert.equal(d.strongest.mmr,5200);s.edit(strong.id,{excluded:false,result:'loss'});assert.equal(s.snapshot().stats.daily.strongest.result,'loss');s.configure({toonHandle:'5-S2-1-9'});assert.equal(s.snapshot().stats.daily.zerglings,0);s.configure({toonHandle:ME.toonHandle});clock=Date.parse('2026-10-06T16:00:00Z');assert.equal(s.snapshot().stats.daily.replayCount,0);
});
test('rescans enrich legacy metrics and opponent MMR once, persist them and never recount results or update own MMR',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'daily-stats-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'records.json');let s=createReplayStore(file,()=>AT+60000);s.configure({toonHandle:ME.toonHandle});s.acceptReplay(parsed(AT,{dailyMetrics:null,opponents:[{...OP,mmr:null}]}),'same');s.updateMMR(5035);assert.equal(s.snapshot().stats.daily.zerglings,null);s=createReplayStore(file,()=>AT+60000);assert.equal(s.acceptReplay(parsed(AT,{selfPlayers:[{...ME,mmr:9999}]}),'same').kind,'duplicate');assert.equal(s.snapshot().stats.total,1);assert.equal(s.snapshot().config.mmr,5035);assert.equal(s.snapshot().stats.daily.zerglings,40);s.acceptReplay(parsed(AT,{dailyMetrics:{version:1,zerglings:null,zealots:null,workersKilled:null}}),'same');assert.equal(s.snapshot().stats.daily.workersKilled,12);assert.equal(createReplayStore(file,()=>AT+60000).snapshot().stats.daily.strongest.mmr,5200);
});
test('daily widget renders safe names, lower bounds and unknowns and honors each scene and its independent switch',()=>{
 const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:false,textContent:'',style:{setProperty(){}},children:[],append(x){this.children.push(x);},replaceChildren(){this.children=[];}});return nodes.get(id);};const window={};const ctx={window,document:{getElementById:node,createElement:()=>({textContent:'',children:[],append(x){this.children.push(x);}}),body:{dataset:{}}}};for(const f of ['daily-model.js','daily-overlay.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../public',f),'utf8'),ctx);
 const s=createReplayStore(null,()=>AT+60000);s.configure({toonHandle:ME.toonHandle,dailyEnabled:true,dailyWaiting:true,dailyGame:false,dailyBreak:true});s.acceptReplay(parsed(),'a');s.acceptReplay(parsed(AT+1000,{dailyMetrics:null,opponents:[{...OP,name:'<script>bad</script>',mmr:6000}]}),'b');const state={scene:'game',ladder:s.snapshot()};window.DailyOverlay.render(state);assert.equal(node('dailyWidget').hidden,true);state.scene='intermission';window.DailyOverlay.render(state);assert.equal(node('dailyWidget').hidden,false);assert.match(node('dailyRows').children[0].children[1].textContent,/≥ 40/);assert.match(node('dailyRows').children[4].children[2].textContent,/<script>bad/);state.scene='break';window.DailyOverlay.render(state);assert.equal(node('dailyWidget').hidden,false);state.ladder.config.dailyEnabled=false;window.DailyOverlay.render(state);assert.equal(node('dailyWidget').hidden,true);window.DailyOverlay.render(state,{sample:true,reveal:true});assert.equal(node('dailyHeading').textContent.includes('示例'),true);
 for(const c of [{dailyEnabled:1},{dailyStyle:'x'},{dailyAccent:'red'},{dailyScale:999},{dailyTitle:'a\n'}])assert.throws(()=>sanitize(c));
});
test('daily draft received before the first state is safe, is isolated to its preview and rejects unrelated fields and origins',()=>{
 let events;const parent={},listeners={},renders=[],node=()=>({style:{},hidden:false});vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../public/ladder-output.js'),'utf8'),{window:{LadderOverlay:{render(){}},ScoreboardOverlay:{render(){}},DailyOverlay:{render:(s,o)=>renders.push({s,o})}},document:{body:{classList:{add(){}}},getElementById:node},location:{search:'?preview=1&module=daily',origin:'http://localhost:1',pathname:'/output'},parent,URLSearchParams,innerWidth:1920,innerHeight:1080,addEventListener:(k,f)=>listeners[k]=f,EventSource:class{constructor(){events=this;}}});const message={origin:'http://localhost:1',source:parent,data:{type:'dailyDraft',config:{dailyX:150,mmr:9999,catEnabled:true,dailyBogus:1},sample:true,phase:'game'}};listeners.message(message);const saved={scene:'intermission',ladder:createReplayStore().snapshot()};events.onmessage({data:JSON.stringify(saved)});const current=renders.at(-1);assert.equal(current.s.scene,'game');assert.equal(current.s.ladder.config.dailyX,150);assert.equal(current.s.ladder.config.mmr,saved.ladder.config.mmr);assert.equal(current.s.ladder.config.dailyBogus,undefined);assert.equal(current.o.sample,true);assert.equal(saved.ladder.config.dailyEnabled,false);listeners.message({...message,origin:'https://evil.example',data:{...message.data,config:{dailyX:999}}});assert.equal(renders.at(-1).s.ladder.config.dailyX,150);
});
test('daily and sponsor routes serve source assets intact and no payment action is exposed',async t=>{const app=createAssistant({port:0,dataDir:null,sc2Reader:async()=>{throw Error('offline');},intervalMs:60000});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const root='http://127.0.0.1:'+app.server.address().port;for(const url of ['/sponsor','/daily-data','/daily-model.js','/daily-overlay.css','/sponsor.js','/sponsor.css','/sponsorship/wechat.png','/sponsorship/alipay.png'])assert.equal((await fetch(root+url)).status,200);const html=await(await fetch(root)).text();assert.match(html,/data-view="daily"/);assert.match(html,/data-view="sponsor"/);assert.doesNotMatch(html,/mailto:/);for(const f of ['wechat.png','alipay.png']){const a=fs.readFileSync(path.join(__dirname,'../public/sponsorship',f)),expected={"wechat.png":"58a5d39fcc5b81b01656415e178c4b3f5f6f36ea44f6cffbef840a63a4c2c2ca","alipay.png":"58a5d39fcc5b81b01656415e178c4b3f5f6f36ea44f6cffbef840a63a4c2c2ca"}[f];assert.equal(require('node:crypto').createHash('sha256').update(a).digest('hex'),expected);}});
