const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),zlib=require('node:zlib'),vm=require('node:vm');
const {createInteractionStore,normalizeBiliEvent,roomNumber,sanitize,csv}=require('../live-interactions.cjs'),{createBilibiliClient,packet,decode,signedHeaders,safeWss}=require('../bilibili-live.cjs'),{createAssistant}=require('../ladder-server.cjs');
const ROOM='123456',AT=Date.parse('2026-10-06T08:00:00Z');
function gift(id,patch={}){return{cmd:'LIVE_OPEN_PLATFORM_SEND_GIFT',data:{room_id:Number(ROOM),msg_id:id,open_id:'viewer-a',uname:'观众甲',gift_name:'测试礼物',gift_num:2,price:1000,paid:true,timestamp:AT/1000,...patch}};}
function chat(id,patch={}){return{cmd:'LIVE_OPEN_PLATFORM_DM',data:{room_id:Number(ROOM),msg_id:id,open_id:id,uname:'观众'+id,msg:'冲分加油',timestamp:AT/1000,...patch}};}
function normalize(raw,now=()=>AT){return normalizeBiliEvent(raw,{roomId:ROOM,now});}
function storeAt(now=()=>AT,options={}){const store=createInteractionStore(null,{now,...options});store.configure({roomId:ROOM});return store;}
const flush=()=>new Promise(r=>setImmediate(r));
function timers(){const list=new Set();return{list,setIntervalImpl(fn,ms){const t={fn,ms,interval:true,unref(){}};list.add(t);return t;},clearIntervalImpl(t){list.delete(t);},setTimeoutImpl(fn,ms){const t={fn,ms,interval:false,unref(){}};list.add(t);return t;},clearTimeoutImpl(t){list.delete(t);}};}
class FakeWS extends EventTarget{static instances=[];constructor(url){super();this.url=url;this.sent=[];FakeWS.instances.push(this);}send(data){this.sent.push(Buffer.from(data));}close(){this.closed=true;this.dispatchEvent(new Event('close'));}emit(type,data){const e=new Event(type);e.data=data;this.dispatchEvent(e);}}
function officialFetch(calls=[]){return async(url,options)=>{calls.push({url,options});const suffix=new URL(url).pathname.split('/').at(-1);return{ok:true,status:200,json:async()=>({code:0,data:suffix==='start'?{game_info:{game_id:'test-game'},anchor_info:{room_id:Number(ROOM),uname:'示例主播'},websocket_info:{auth_body:'{"roomid":123456,"key":"test-auth"}',wss_link:['wss://broadcastlv.chat.bilibili.com/sub']}}:{}})};};}
const KEYS={appId:'1234567890123456789',accessKeyId:'test-access',accessKeySecret:'test-secret-not-real',code:'test-code-not-real'};
test('room links and appearance accept valid Bilibili rooms only, while income settings reject invalid rates',()=>{
 assert.equal(roomNumber('http://live.bilibili.com/123456?x=1'),ROOM);assert.equal(roomNumber(123456),ROOM);for(const value of ['https://evil.example/123456','https://live.bilibili.com.evil.example/123456','../123456','0','1e5'])assert.throws(()=>roomNumber(value));
 for(const c of [{giftEnabled:'true'},{giftX:-1},{raffleWidth:9999},{accent:'url(x)'},{shareBps:10001},{shareBps:0.5}])assert.throws(()=>sanitize(c));
});
test('official and public gift formats keep currency units, quantities and unpaid status; ambiguous prices stay unknown',()=>{
 const e=normalize(gift('a'));assert.equal(e.valueMilli,2000);assert.equal(e.quantity,2);assert.equal(e.userId,'viewer-a');assert.equal(e.paid,true);
 assert.equal(normalize(gift('b',{paid:false})).valueMilli,0);assert.equal(normalize(gift('c',{blind_gift:{status:true},price:999999})).valueMilli,null);assert.equal(normalize(gift('d',{gift_num:0})),null);
 const publicGift=normalize({cmd:'SEND_GIFT',data:{uid:5,uname:'观众',giftName:'辣条',num:3,price:100,coin_type:'gold',timestamp:AT/1000}});assert.equal(publicGift.valueMilli,300);
 assert.equal(normalize({cmd:'LIVE_OPEN_PLATFORM_SUPER_CHAT',data:{room_id:Number(ROOM),msg_id:'sc1',message_id:8,open_id:'b',uname:'B',rmb:30,message:'加油',timestamp:AT/1000}}).valueMilli,30000);
 assert.equal(normalize({cmd:'LIVE_OPEN_PLATFORM_GUARD',data:{room_id:Number(ROOM),msg_id:'guard1',user_info:{open_id:'b',uname:'B'},guard_level:3,guard_num:1,price:198000,timestamp:AT/1000}}).valueMilli,null);
 assert.equal(normalize({cmd:'OPEN_LIVEROOM_DM',data:chat('x').data}).type,'chat');assert.equal(normalize(chat('x',{open_id:'',uname:'匿名'})),null);
});
test('deduplicated gift accounting survives restart, stays room and Beijing-day specific and isolates manual settlement',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'live-ledger-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'live.json');let at=AT;const store=createInteractionStore(file,{now:()=>at});store.configure({roomId:ROOM});
 const a=normalize(gift('a'));assert.equal(store.ingest(a),true);assert.equal(store.ingest(a),false);store.ingest(normalize(gift('free',{paid:false,gift_num:5})));store.ingest(normalize(gift('blind',{blind_gift:{status:true}})));store.ingest({...normalize(gift('other')),roomId:'777'});
 store.updateIncome({shareBps:5000,costMilli:500,settledMilli:600});let s=store.snapshot().summary;assert.equal(s.paidMilli,2000);assert.equal(s.freeCount,5);assert.equal(s.unknownCount,1);assert.equal(s.estimatedMilli,1000);assert.equal(s.afterCostMilli,500);assert.equal(s.settledMilli,600);
 const restored=createInteractionStore(file,{now:()=>at});assert.equal(restored.ingest(a),false);assert.deepEqual(restored.snapshot().summary,s);restored.configure({roomId:'777'});assert.equal(restored.snapshot().summary.paidMilli,0);restored.configure({roomId:ROOM});assert.equal(restored.snapshot().summary.paidMilli,2000);
 at=Date.parse('2026-10-06T16:00:00Z');s=restored.snapshot().summary;assert.equal(s.date,'2026-10-07');assert.equal(s.paidMilli,0);assert.equal(s.settledMilli,null);assert.equal(s.costMilli,0);
});
test('income updates validate atomically; exclusions are reversible and SC removal does not invent a refund',()=>{
 const store=storeAt();store.ingest(normalize(gift('a')));const before=store.snapshot();assert.throws(()=>store.updateIncome({shareBps:5000,costMilli:-1,settledMilli:null}));assert.deepEqual(store.snapshot(),before);store.excludeGift('a',true);assert.equal(store.snapshot().summary.paidMilli,0);store.excludeGift('a',false);assert.equal(store.snapshot().summary.paidMilli,2000);
 store.ingest(normalize({cmd:'OPEN_LIVEROOM_SUPER_CHAT',data:{room_id:Number(ROOM),msg_id:'sc',message_id:7,open_id:'b',uname:'B',rmb:30,timestamp:AT/1000}}));store.ingest(normalize({cmd:'OPEN_LIVEROOM_SUPER_CHAT_DEL',data:{room_id:Number(ROOM),message_ids:[7]}}));assert.equal(store.snapshot().summary.paidMilli,32000);assert.equal(store.snapshot().gifts.find(g=>g.id==='sc').retracted,true);
});
test('raffle enrolls only exact eligible chat, deduplicates viewer IDs across renames, freezes at deadline and never auto-draws',()=>{
 let at=AT;const store=storeAt(()=>at,{randomInt:()=>0});store.startRound({title:'示例奖品',keyword:'冲分加油',winnerCount:1,seconds:15});store.ingest(normalize(chat('a'),()=>at));store.ingest(normalize(chat('a',{msg_id:'rename',uname:'新昵称'}),()=>at));store.ingest(normalize(chat('b',{msg:'我说冲分加油'}),()=>at));store.ingest({...normalize(chat('c'),()=>at),roomId:'999'});store.ingest(normalize(chat('old',{timestamp:(AT-5000)/1000}),()=>at));assert.equal(store.snapshot().raffle.count,1);assert.throws(()=>store.draw());
 at=AT+15000;store.ingest(normalize(chat('late',{timestamp:at/1000}),()=>at));assert.equal(store.snapshot().raffle.status,'closed');assert.equal(store.snapshot().raffle.count,1);assert.equal(store.snapshot().raffle.winners.length,0);store.draw();assert.equal(store.snapshot().raffle.winners[0].name,'观众a');assert.throws(()=>store.draw(),'cannot reroll');
});
test('registration and drawn winners persist; invalid imports are atomic and manual IDs deduplicate with chat',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'live-raffle-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'live.json');let at=AT;let store=createInteractionStore(file,{now:()=>at,randomInt:()=>0});store.configure({roomId:ROOM});store.startRound({title:'奖品',keyword:'冲分加油',winnerCount:2,seconds:30});store.ingest(normalize(chat('a')));assert.throws(()=>store.importEntries('b\tB\ninvalid line'));assert.equal(store.snapshot().raffle.count,1);store.importEntries('a\t重复的A\nb\t观众乙');assert.equal(store.snapshot().raffle.count,2);assert.throws(()=>store.configure({roomId:'999'}));
 store=createInteractionStore(file,{now:()=>at,randomInt:()=>0});assert.equal(store.snapshot().raffle.status,'collecting');assert.equal(store.snapshot().raffle.count,2);at+=30000;assert.equal(store.snapshot().raffle.status,'closed');store.draw();const winners=store.snapshot().raffle.winners;assert.equal(new Set(winners.map(w=>w.name)).size,2);assert.deepEqual(createInteractionStore(file,{now:()=>at}).snapshot().raffle.winners,winners);assert.match(store.exportCSV('winners'),/手动补充/);
});
test('insufficient entries cannot draw, cancellation is retained, and a later round does not erase previous winners',()=>{
 const store=storeAt();store.startRound({title:'A',keyword:'冲分加油',winnerCount:2,seconds:15});store.ingest(normalize(chat('a')));store.closeRound();assert.throws(()=>store.draw());assert.equal(store.snapshot().raffle.status,'closed');store.changeWinnerCount(1);store.draw();store.startRound({title:'B',keyword:'开始',winnerCount:1,seconds:15});store.cancelRound();assert.equal(store.snapshot().raffle.status,'cancelled');assert.equal(store.snapshot().history.length,1);assert.equal(store.snapshot().history[0].title,'A');
});
test('CSV exports include exact amounts and neutralize formulas in viewer names and prizes',()=>{
 const store=storeAt();store.ingest(normalize(gift('csv',{uname:'=HYPERLINK("evil")'})));const exported=store.exportCSV('income');assert.ok(exported.startsWith('\ufeff'));assert.match(exported,/'=HYPERLINK/);assert.match(exported,/2\.000/);assert.match(csv([['@SUM(1)', 'a,"b']]),/'@SUM/);assert.throws(()=>store.exportCSV('winners'));
});
test('Bilibili packet decoding handles concatenation, zlib and Brotli and rejects oversized or malformed payloads',()=>{
 const p=packet(5,JSON.stringify(gift('p')),0),q=packet(8,'{"code":0}',1);assert.equal(decode(Buffer.concat([p,q])).length,2);for(const [version,compress]of [[2,zlib.deflateSync],[3,zlib.brotliCompressSync]])assert.equal(decode(packet(5,compress(Buffer.concat([p,q])),version))[0].data.data.msg_id,'p');assert.throws(()=>decode(Buffer.alloc(15)));const bad=Buffer.from(p);bad.writeUInt32BE(p.length+1);assert.throws(()=>decode(bad));assert.throws(()=>decode(packet(5,Buffer.from('x'),9)));assert.throws(()=>decode(packet(5,zlib.deflateSync(Buffer.alloc(5*1024*1024)),2)));
});
test('official request signing is deterministic, body-bound and never contains the plain secret',()=>{
 const h=signedHeaders('{"code":"hello","app_id":1}','access','secret',{now:()=>1700000000000,nonce:()=> 'fixed-nonce'});assert.equal(h['x-bili-timestamp'],'1700000000');assert.equal(h['x-bili-content-md5'],crypto.createHash('md5').update('{"code":"hello","app_id":1}').digest('hex'));assert.match(h.Authorization,/^[a-f\d]{64}$/);assert.equal(Object.values(h).includes('secret'),false);assert.notEqual(h.Authorization,signedHeaders('{"code":"other","app_id":1}','access','secret',{now:()=>1700000000000,nonce:()=> 'fixed-nonce'}).Authorization);
 assert.throws(()=>safeWss('ws://broadcastlv.chat.bilibili.com/sub'));assert.throws(()=>safeWss('wss://evil.example/sub'));assert.throws(()=>safeWss('wss://bilibili.com.evil.example/sub'));
});
test('public-room refusal reports a real connection error without a fake websocket or connected status',async()=>{
 let requests=0,wsCount=0;const client=createBilibiliClient({fetchImpl:async url=>{requests++;return{ok:true,status:200,json:async()=>new URL(url).pathname.includes('room_init')?{code:0,data:{room_id:Number(ROOM)}}:{code:-352}};},WebSocketImpl:class{constructor(){wsCount++;}},...timers()});await client.connect({mode:'public',roomId:ROOM});assert.equal(requests,2);assert.equal(wsCount,0);assert.equal(client.snapshot().status,'error');assert.match(client.snapshot().message,/-352/);assert.equal(client.snapshot().roomId,ROOM);client.close();
});
test('official connection waits for successful websocket auth, preserves int64 app ID, parses events and cleans up the session',async()=>{
 const calls=[],events=[],clock=timers();const client=createBilibiliClient({fetchImpl:officialFetch(calls),WebSocketImpl:FakeWS,now:()=>AT,...clock,onEvent:e=>events.push(e)});await client.connect({mode:'official',roomId:ROOM,credentials:KEYS});assert.equal(client.snapshot().status,'authenticating');assert.ok(calls[0].options.body.includes('"app_id":1234567890123456789'));assert.equal(calls[0].options.body.includes(KEYS.accessKeySecret),false);assert.equal(JSON.stringify(client.snapshot()).includes(KEYS.accessKeySecret),false);
 const ws=FakeWS.instances.at(-1);ws.emit('open');assert.equal(ws.sent[0].readUInt32BE(8),7);ws.emit('message',packet(8,'{"code":0}'));await flush();assert.equal(client.snapshot().status,'connected');ws.emit('message',packet(5,JSON.stringify(gift('ws')),0));await flush();assert.equal(events.length,1);assert.equal(events[0].valueMilli,2000);await client.disconnect();assert.equal(client.snapshot().status,'disconnected');assert.equal(client.snapshot().credentialsLoaded,false);assert.equal(clock.list.size,0);assert.ok(calls.some(c=>c.url.endsWith('/end')));ws.emit('message',packet(5,JSON.stringify(gift('late')),0));await flush();assert.equal(events.length,1);
});
test('websocket auth rejection cannot accept gifts; reconnect timers stop when disconnected',async()=>{
 const events=[],clock=timers(),client=createBilibiliClient({fetchImpl:officialFetch(),WebSocketImpl:FakeWS,...clock,onEvent:e=>events.push(e)});await client.connect({mode:'official',roomId:ROOM,credentials:KEYS});let ws=FakeWS.instances.at(-1);ws.emit('open');ws.emit('message',packet(8,'{"code":-101}'));await flush();assert.equal(client.snapshot().status,'error');assert.equal(clock.list.size,0);assert.equal(client.snapshot().credentialsLoaded,false);
 await client.connect({mode:'official',roomId:ROOM,credentials:KEYS});ws=FakeWS.instances.at(-1);ws.emit('open');ws.emit('message',packet(8,'{"code":0}'));await flush();ws.close();assert.equal(client.snapshot().status,'reconnecting');await client.disconnect();assert.equal(clock.list.size,0);assert.equal(events.length,0);
});
test('official identity code must belong to the chosen room; short-room aliases resolve before verification',async()=>{
 for(const [resolved,expected]of [[123456,'authenticating'],[999999,'error']]){const calls=[],base=officialFetch(calls),rooms=[];const client=createBilibiliClient({fetchImpl:async(url,options)=>url.includes('room_init')?{ok:true,status:200,json:async()=>({code:0,data:{room_id:resolved}})}:base(url,options),WebSocketImpl:FakeWS,...timers(),onRoom:r=>rooms.push(r)});await client.connect({mode:'official',roomId:'12345',credentials:KEYS});assert.equal(client.snapshot().status,expected);if(expected==='error'){assert.match(client.snapshot().message,/不一致/);assert.deepEqual(rooms,[]);assert.equal(client.snapshot().credentialsLoaded,false);await flush();assert.ok(calls.some(c=>c.url.endsWith('/end')));}else assert.deepEqual(rooms,[ROOM]);await client.disconnect();}
});
test('API authenticates ingestion and exports, keeps interaction records separate from ladder results and serves the UI',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'live-api-'));const app=createAssistant({port:0,dataDir:dir,now:()=>AT,sc2Reader:async()=>{throw Error('offline');},intervalMs:60000});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>{app.close();fs.rmSync(dir,{recursive:true,force:true});});const root='http://127.0.0.1:'+app.server.address().port,html=await(await fetch(root)).text(),token=html.match(/name="control-token" content="([^"]+)"/)[1];const post=(body,auth=token,origin=root)=>fetch(root+'/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Control-Token':auth,Origin:origin},body:JSON.stringify(body)});
 const ladderBefore=app.ladder.snapshot();assert.equal((await post({action:'liveConfigure',config:{roomId:ROOM}},'bad')).status,403);assert.equal((await post({action:'liveConfigure',config:{roomId:ROOM}},token,'https://evil.example')).status,403);await post({action:'liveConfigure',config:{roomId:ROOM}});await post({action:'liveEvent',event:gift('http')});await post({action:'liveEvent',event:gift('http')});assert.equal(app.interactions.snapshot().summary.paidMilli,2000);assert.deepEqual(app.ladder.snapshot(),ladderBefore);
 assert.equal((await fetch(root+'/api/live-export?kind=income')).status,403);const report=await fetch(root+'/api/live-export?kind=income',{headers:{'X-Control-Token':token}});assert.equal(report.status,200);assert.match(await report.text(),/测试礼物/);
 await post({action:'liveRaffleStart',title:'奖品',keyword:'冲分加油',winnerCount:1,seconds:30});await post({action:'liveEvent',event:chat('viewer')});await post({action:'liveRaffleClose'});assert.equal((await post({action:'liveRaffleDraw'})).status,200);assert.equal((await post({action:'liveRaffleDraw'})).status,400);assert.equal(createInteractionStore(path.join(dir,'live-interactions.json'),{now:()=>AT}).snapshot().raffle.winners.length,1);
 for(const url of ['/live-interaction','/live-overlay.js','/live-overlay.css','/live-workspace.js','/live-workspace.css'])assert.equal((await fetch(root+url)).status,200,url);assert.match(html,/data-view="liveinteraction"[^>]+hidden/);
});
test('overlay demo messages are parent-origin gated, expire locally, show text safely and never invoke real ingestion',()=>{
 let at=AT,events;const listeners={},nodes=new Map(),parent={},node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:true,textContent:'',style:{setProperty(){}},classList:{add(){},toggle(){}}});return nodes.get(id);};const store=storeAt(()=>at),saved={serverNow:at,ladder:{config:{gameFrameAccent:'#c5dc8e'}},interaction:store.snapshot()},calls=[];const fakeDate={now:()=>at};const window={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../public/live-overlay.js'),'utf8'),{window,document:{getElementById:node,body:{dataset:{liveSource:'true'},classList:{add(){}}}},location:{origin:'http://localhost:1',search:'?preview=1'},parent,Date:fakeDate,URLSearchParams,innerWidth:1920,innerHeight:1080,setInterval:f=>calls.push(f),addEventListener:(k,f)=>listeners[k]=f,EventSource:class{constructor(){events=this;}}});events.onmessage({data:JSON.stringify(saved)});assert.equal(node('liveGift').hidden,true);
 const demo={origin:'http://localhost:1',source:parent,data:{type:'liveDemo',kind:'gift'}};listeners.message({...demo,origin:'https://evil.example'});assert.equal(node('liveGift').hidden,true);listeners.message(demo);assert.equal(node('liveGift').hidden,false);assert.equal(node('liveGiftName').textContent,'示例观众');assert.equal(store.snapshot().summary.paidMilli,0);at+=8000;calls[0]();assert.equal(node('liveGift').hidden,true);
 listeners.message({origin:'http://localhost:1',source:parent,data:{type:'liveDemo',kind:'raffle'}});assert.equal(node('liveOverlayWinners').textContent,'示例中奖观众');assert.equal(store.snapshot().raffle,null);at+=11000;calls[0]();assert.equal(node('liveRaffle').hidden,true);
});
