const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const {createReplayStore,sanitize}=require('../ladder-replays.cjs');
const at=Date.parse('2026-10-06T10:00:00Z'),me={toonHandle:'5-S2-1-1',name:'Me',human:true,race:'Terran',mmr:4000},op={toonHandle:'5-S2-1-2',name:'Other',human:true,race:'Zerg',mmr:4000};
const parsed=(extra={})=>({ok:true,at,durationSeconds:600,map:'测试地图',players:[me,op],selfPlayers:[me],opponents:[op],selfResult:'W',...extra});
test('longest match follows current account and Beijing day, exclusions, valid replay durations and corrections',()=>{
 let clock=at+60000;const store=createReplayStore(null,()=>clock);store.configure({toonHandle:me.toonHandle});assert.equal(store.snapshot().stats.longestMatch,null);
 store.acceptReplay(parsed(),'short');store.acceptReplay(parsed({at:at+10000,durationSeconds:1801,selfResult:'L'}),'long');store.acceptReplay(parsed({at:at-86400000,durationSeconds:7200}),'yesterday');store.acceptReplay(parsed({at:at+20000,durationSeconds:null}),'missing');store.acceptReplay(parsed({at:at+30000,durationSeconds:'99999'}),'invalid');
 let longest=store.snapshot().stats.longestMatch;assert.equal(longest.durationSeconds,1801);assert.equal(longest.result,'loss');store.edit(longest.id,{result:'win'});assert.equal(store.snapshot().stats.longestMatch.result,'win');store.edit(longest.id,{excluded:true});assert.equal(store.snapshot().stats.longestMatch.durationSeconds,600);store.edit(longest.id,{excluded:false});
 store.configure({toonHandle:'5-S2-1-9'});assert.equal(store.snapshot().stats.longestMatch,null);store.add('win');assert.equal(store.snapshot().stats.longestMatch,null);store.configure({toonHandle:me.toonHandle});assert.equal(store.snapshot().stats.longestMatch.durationSeconds,1801);clock+=86400000;assert.equal(store.snapshot().stats.longestMatch,null);
});
test('duplicate rescans fill legacy duration without adding results or changing MMR; longest survives restart',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'longest-match-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'data.json');let store=createReplayStore(file,()=>at+60000);store.configure({toonHandle:me.toonHandle});store.acceptReplay(parsed({durationSeconds:null}),'same-hash');const before=store.snapshot();assert.equal(before.stats.longestMatch,null);
 store=createReplayStore(file,()=>at+60000);assert.equal(store.acceptReplay(parsed({durationSeconds:1500}),'same-hash').kind,'duplicate');assert.equal(store.snapshot().stats.total,1);assert.equal(store.snapshot().config.mmr,before.config.mmr);assert.equal(store.snapshot().stats.longestMatch.durationSeconds,1500);assert.equal(createReplayStore(file,()=>at+60000).snapshot().stats.longestMatch.durationSeconds,1500);
 store.configure({waitingShowLongest:true,breakShowLongest:false});const config=createReplayStore(file,()=>at+60000).getConfig();assert.equal(config.waitingShowLongest,true);assert.equal(config.breakShowLongest,false);assert.throws(()=>sanitize({waitingShowLongest:1}));
});
test('longest match resets at Beijing midnight even when both records share a UTC date',()=>{
 const midnight=Date.parse('2026-10-05T16:00:00Z'),store=createReplayStore(null,()=>midnight+60000);store.configure({toonHandle:me.toonHandle});store.acceptReplay(parsed({at:midnight-1000,durationSeconds:7200}),'before-midnight');store.acceptReplay(parsed({at:midnight+1000,durationSeconds:1200}),'after-midnight');assert.equal(store.snapshot().date,'2026-10-06');assert.equal(store.snapshot().stats.longestMatch.durationSeconds,1200);
});
test('waiting longest card is independent of scoreboard visibility, escapes via textContent and hides when absent or disabled',()=>{
 const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:false,textContent:'',innerHTML:'',style:{setProperty(){}},parentElement:{hidden:false},getAttribute(){return '';}});return nodes.get(id);},win={};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../public/ladder-overlay.js'),'utf8'),{window:win,document:{getElementById:node}});const store=createReplayStore(null,()=>at+60000);store.configure({waitingShowLongest:true,scoreboardEnabled:false});const state={scene:'intermission',ladder:store.snapshot()};win.LadderOverlay.render(state);assert.equal(node('waitingLongest').hidden,true);
 state.ladder.stats.longestMatch={durationSeconds:1801,opponent:'<img src=x>',map:'地图',result:'win'};win.LadderOverlay.render(state);assert.equal(node('waitingLongest').hidden,false);assert.equal(node('waitingRecord').parentElement.hidden,false,'waiting statistics have their own switch');assert.equal(node('waitingLongestTime').textContent,'30:01');assert.match(node('waitingLongestDetail').textContent,/<img src=x>/);assert.equal(node('waitingLongestDetail').innerHTML,'');state.ladder.config.waitingShowLongest=false;win.LadderOverlay.render(state);assert.equal(node('waitingLongest').hidden,true);state.scene='game';win.LadderOverlay.render(state);assert.equal(node('ladderWaiting').hidden,true);
});
test('scoreboard and HUD preview drafts stay local and reject unrelated fields and origins',()=>{
 function harness(module){let events;const listeners={},renders=[],parent={};vm.runInNewContext(require('./preview-fixture.cjs')+fs.readFileSync(path.join(__dirname,'../public/ladder-output.js'),'utf8'),{location:{search:'?preview=1&phase=game&module='+module,origin:'http://localhost:1'},parent,URLSearchParams,innerWidth:1920,innerHeight:1080,document:{body:{classList:{add(){}}},getElementById:()=>({style:{},hidden:false})},addEventListener:(k,fn)=>listeners[k]=fn,window:{LadderOverlay:{render:s=>renders.push(s)},ScoreboardOverlay:{render(){}}},EventSource:class{constructor(){events=this;}}});return{events,listeners,renders,parent};}
 const saved={scene:'intermission',ladder:createReplayStore().snapshot()},score=harness('scoreboard');score.events.onmessage({data:JSON.stringify(saved)});score.listeners.message({origin:'http://localhost:1',source:score.parent,data:{type:'scoreboardDraft',config:{scoreboardX:32,scoreboardTemplate:'dual',mmr:9999,waitingTitle:'bad'}}});let c=score.renders.at(-1).ladder.config;assert.equal(c.scoreboardX,32);assert.equal(c.scoreboardTemplate,'dual');assert.equal(c.mmr,saved.ladder.config.mmr);assert.equal(c.waitingTitle,saved.ladder.config.waitingTitle);assert.equal(saved.ladder.config.scoreboardX,1328);
 score.listeners.message({origin:'https://example.com',source:score.parent,data:{type:'scoreboardDraft',config:{scoreboardX:555}}});assert.equal(score.renders.at(-1).ladder.config.scoreboardX,32);
 const hud=harness('overlay');hud.events.onmessage({data:JSON.stringify(saved)});hud.listeners.message({origin:'http://localhost:1',source:hud.parent,data:{type:'hudDraft',config:{template:'dual',title:'预览标题',x:55,catEnabled:true,mmr:9999}}});c=hud.renders.at(-1).ladder.config;assert.equal(c.template,'dual');assert.equal(c.title,'预览标题');assert.equal(c.x,55);assert.equal(c.catEnabled,saved.ladder.config.catEnabled);assert.equal(c.mmr,saved.ladder.config.mmr);
});
