const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm'),{EventEmitter}=require('node:events'),{PassThrough}=require('node:stream');
const packs=require('../public/outfit-presets.js'),{createReplayStore,sanitize,defaults}=require('../ladder-replays.cjs'),{createAssistant}=require('../ladder-server.cjs');
const read=f=>fs.readFileSync(path.join(__dirname,'../public',f),'utf8');
test('all five coordinated outfits validate and preserve identity, records, switches, positions and personal text',()=>{
 const store=createReplayStore();store.configure({names:['Me'],toonHandle:'5-S2-1-123',waitingTitle:'我的等待',breakTitle:'我的暂离',waitingKicker:'自定义标语',catKeyboardSide:'right',catView:'rear',scoreboardEnabled:false,showHUD:false,waitingShowLongest:true,scoreboardX:100,catX:1300,gameFrameOpacity:75});store.add('win');store.updateMMR(5035);
 for(const [id,p]of Object.entries(packs.presets)){const before=store.snapshot(),patch=packs.buildPatch(before.config,{preset:id}),next=sanitize(patch,before.config);store.configure(patch);const saved=store.snapshot();assert.equal(next.gameFrameStyle,p.frame);assert.equal(next.catCharacter,p.cat);assert.equal(next.waitingTheme,p.scene);assert.equal(next.breakTheme,p.scene);assert.equal(next.scoreboardAccent,p.accent);for(const k of ['names','toonHandle','waitingTitle','breakTitle','waitingKicker','catKeyboardSide','catView','scoreboardEnabled','showHUD','waitingShowLongest','scoreboardX','catX','gameFrameOpacity','mmr','mmrSource'])assert.deepEqual(next[k],before.config[k],k);assert.deepEqual(saved.records,before.records);assert.deepEqual(saved.stats,before.stats);}
});
test('scoped outfits replace media by default and preserve it only when explicitly requested',()=>{
 const c={...defaults,waitingBackground:'video',waitingBackgroundVideo:'/scene-media/'+'b'.repeat(64)+'.webm',breakBackground:'image',breakBackgroundImage:'/waiting-backgrounds/'+'a'.repeat(64)+'.png',waitingLayout:'right',waitingWidth:900};
 const patch=packs.buildPatch(c,{preset:'nahida',modules:['waiting'],preserveLayout:true,preserveMedia:true});assert.equal(patch.waitingTheme,'nahida');for(const k of ['waitingBackground','waitingBackgroundVideo','waitingLayout','waitingWidth','breakTheme','gameFrameStyle','catCharacter'])assert.equal(Object.hasOwn(patch,k),false,k);
 const switched=packs.buildPatch(c,{preset:'nahida',modules:['waiting','catkeyboard'],preserveMedia:false,preserveLayout:false,enableTools:true});assert.equal(switched.waitingBackground,'gradient');assert.equal(switched.waitingLayout,'left');assert.equal(switched.waitingWidth,1080);assert.equal(switched.catEnabled,true);assert.equal(Object.hasOwn(switched,'enabled'),false);assert.equal(Object.hasOwn(switched,'waitingBackgroundVideo'),false,'uploaded file stays available');assert.equal(Object.hasOwn(switched,'scoreboardEnabled'),false);
 assert.equal(packs.buildPatch(defaults,{preset:'vesna',modules:['break']}).breakKicker,'VESNA / 雪宴之风');
});
test('outfit choices reject unknown presets, arbitrary field names, malformed flags and empty scope',()=>{
 for(const input of [null,{},[],{preset:'constructor'},{preset:'../x'},{preset:'anes',modules:[]},{preset:'anes',modules:['names']},{preset:'anes',modules:['waiting','waiting']},{preset:'anes',preserveMedia:1},{preset:'anes',enableTools:'true'}])assert.throws(()=>packs.buildPatch(defaults,input));
 for(const scoreboardAccent of ['red','url(x)',null,123])assert.throws(()=>sanitize({scoreboardAccent}));assert.equal(sanitize({scoreboardAccent:''}).scoreboardAccent,'');
});
test('authenticated outfit actions apply once, persist all selected modules and support a safe scoped undo',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'outfit-api-'));const worker=()=>{const w=new EventEmitter();w.stdout=new PassThrough();w.stderr=new PassThrough();w.kill=()=>{};return w;};
 const app=createAssistant({port:0,dataDir:dir,sc2Reader:async()=>{throw Error('offline');},intervalMs:60000,keyboardSpawn:worker});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>{app.close();fs.rmSync(dir,{recursive:true,force:true});});
 const url='http://127.0.0.1:'+app.server.address().port,html=await(await fetch(url)).text(),token=html.match(/name="control-token" content="([^"]+)"/)[1];const action=(body,auth=token,origin=url)=>fetch(url+'/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-Control-Token':auth,Origin:origin},body:JSON.stringify(body)});
 app.ladder.configure({autoTrack:false,names:['Me'],toonHandle:'5-S2-1-123',scoreboardX:77});app.ladder.add('win');app.ladder.updateMMR(5035);const before=app.ladder.snapshot();
 assert.equal((await action({action:'outfitApply',choice:{preset:'nahida'}},'bad')).status,403);assert.equal((await action({action:'outfitApply',choice:{preset:'nahida'}},token,'https://example.com')).status,403);
 assert.equal((await action({action:'outfitApply',choice:{preset:'nahida',modules:['names']}})).status,400);assert.deepEqual(app.ladder.snapshot(),before);
 const response=await action({action:'outfitApply',choice:{preset:'nahida'}});assert.equal(response.status,200);const next=await response.json();assert.equal(next.outfit.canUndo,true);assert.equal(next.scene,'intermission');assert.equal(next.ladder.config.catCharacter,'nahida');assert.deepEqual(next.ladder.records,JSON.parse(JSON.stringify(before.records)));assert.equal(createReplayStore(path.join(dir,'records.json')).getConfig().breakTheme,'nahida');
 app.ladder.updateMMR(5050);app.ladder.add('loss');assert.equal((await action({action:'outfitUndo'})).status,200);const restored=app.ladder.snapshot();assert.equal(restored.config.catCharacter,before.config.catCharacter);assert.equal(restored.config.mmr,5050);assert.equal(restored.stats.total,2);
 await action({action:'outfitApply',choice:{preset:'vesna',modules:['gameframe']}});app.ladder.configure({gameFrameAccent:'#112233'});assert.equal((await action({action:'outfitUndo'})).status,400);assert.equal(app.ladder.getConfig().gameFrameAccent,'#112233');assert.equal((await(await fetch(url+'/api/state')).json()).outfit.canUndo,false);
 for(const route of ['/outfit-presets.js','/outfit-workspace.js','/outfit-workspace.css'])assert.equal((await fetch(url+route)).status,200,route);
});
test('outfit preview accepts trusted choices only, supports all three scenes, avoids live keyboard capture and never writes live output',()=>{
 function harness(search){let events;const listeners={},renders=[],catCalls=[],nodes={},parent={};const node=id=>nodes[id]??=( {hidden:false,style:{}} );vm.runInNewContext(read('ladder-output.js'),{location:{search,pathname:'/output',origin:'http://localhost:1'},parent,URLSearchParams,innerWidth:1920,innerHeight:1080,document:{body:{classList:{add(){}}},getElementById:node},addEventListener:(k,f)=>listeners[k]=f,window:{OutfitPresets:packs,LadderOverlay:{render:s=>renders.push(s)},ScoreboardOverlay:{render(){}},CatKeyboardOverlay:{render:(s,o)=>catCalls.push(o)}},EventSource:class{constructor(){events=this;}}});return{events,listeners,renders,parent,catCalls,nodes};}
 const saved={scene:'game',ladder:createReplayStore().snapshot()},h=harness('?preview=1&module=outfit');h.events.onmessage({data:JSON.stringify(saved)});const message={origin:'http://localhost:1',source:h.parent,data:{type:'outfitDraft',choice:{preset:'nahida'},phase:'break',reveal:true,config:{name:'fake'}}};h.listeners.message(message);assert.equal(h.renders.at(-1).scene,'break');assert.equal(h.renders.at(-1).ladder.config.breakTheme,'nahida');assert.equal(h.renders.at(-1).ladder.config.name,saved.ladder.config.name);assert.equal(h.catCalls.at(-1).preview,true);assert.equal(h.nodes.catWidget.hidden,true);
 for(const bad of [{...message,origin:'https://example.com'},{...message,source:{}},{...message,data:{...message.data,choice:{preset:'unknown'}}}])h.listeners.message(bad);assert.equal(h.renders.at(-1).ladder.config.breakTheme,'nahida');
 h.listeners.message({...message,data:{...message.data,phase:'game'}});assert.equal(h.nodes.catWidget.hidden,false);h.listeners.message({...message,data:{...message.data,phase:'intermission'}});assert.equal(h.renders.at(-1).scene,'intermission');assert.equal(saved.ladder.config.waitingTheme,'team');
 const live=harness('');live.events.onmessage({data:JSON.stringify(saved)});assert.equal(live.listeners.message,undefined);assert.equal(live.renders.at(-1).ladder.config.catCharacter,saved.ladder.config.catCharacter);
});
