const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{create,attachHost}=require('../public/preview-connection.js'),{createAssistant}=require('../ladder-server.cjs');
const state=revision=>({serverInstanceId:'test',revision,ladder:{config:{catCharacter:'artanis'}}});
function harness(embedded){const handlers=new Map(),timers=new Map(),sent=[],states=[],streams=[];let id=0;const scope={location:{origin:'http://localhost:1',href:'http://localhost:1/'},addEventListener:(k,f)=>handlers.set(k,f),removeEventListener:k=>handlers.delete(k),parent:null};scope.parent=embedded?{postMessage:(m,o)=>sent.push({m,o})}:scope;const c=create({preview:true,scope,onState:s=>states.push(s),EventSourceImpl:class{constructor(url){this.url=url;streams.push(this);}close(){this.closed=true;}},setTimeoutImpl:f=>{timers.set(++id,f);return id;},clearTimeoutImpl:i=>timers.delete(i)});return{c,scope,handlers,timers,sent,states,streams};}
test('embedded preview uses no HTTP connection, requests current state and accepts only its own same-origin parent',()=>{
 const h=harness(true);assert.equal(h.streams.length,0);assert.equal(h.sent[0].m.type,'previewReady');assert.equal(h.timers.size,1);const receive=h.handlers.get('message'),message={origin:h.scope.location.origin,source:h.scope.parent,data:{type:'previewState',state:state(4)}};receive({...message,origin:'https://evil.example'});receive({...message,source:{}});assert.equal(h.states.length,0);receive(message);assert.equal(h.states.length,1);assert.equal(h.timers.size,0);receive({...message,data:{...message.data,state:state(3)}});assert.equal(h.states.length,1);receive({...message,data:{...message.data,state:{...state(0),serverInstanceId:'restart'}}});assert.equal(h.states.length,2);h.c.close();receive(message);assert.equal(h.states.length,2);assert.equal(h.handlers.size,0);
});
test('standalone preview keeps one live stream and releases it when the page leaves',()=>{const h=harness(false);assert.equal(h.streams.length,1);assert.equal(h.streams[0].url,'/api/events?role=preview');h.streams[0].onmessage({data:JSON.stringify(state(1))});assert.equal(h.states.length,1);h.handlers.get('pagehide')();assert.equal(h.streams[0].closed,true);h.streams[0].onmessage({data:JSON.stringify(state(2))});assert.equal(h.states.length,1);});
test('host shares state only with active known preview frames and never responds to unrelated windows or origins',()=>{
 const messages=[],listeners={},scope={location:{origin:'http://localhost:1',href:'http://localhost:1/'},addEventListener:(k,f)=>listeners[k]=f,removeEventListener:k=>delete listeners[k]};const frame=(src,hidden=false)=>({getAttribute:()=>src,closest:()=>({hidden}),contentWindow:{postMessage:(m,o)=>messages.push({m,o,src})}});const frames=[frame('/output?preview=1'),frame('/cat-keyboard?preview=1'),frame('/gameframe?preview=1',true),frame('/output'),frame('https://evil.example/output?preview=1'),frame('/unknown?preview=1')];const h=attachHost({scope,documentImpl:{querySelectorAll:()=>frames},getState:()=>state(2)});h.publish(state(1));assert.equal(messages.length,2);const ready={origin:scope.location.origin,source:frames[0].contentWindow,data:{type:'previewReady'}};listeners.message({...ready,origin:'https://evil.example'});listeners.message({...ready,source:{}});assert.equal(messages.length,2);listeners.message(ready);assert.equal(messages.length,3);assert.equal(messages.at(-1).m.state.revision,2);h.close();assert.equal(listeners.message,undefined);
});
test('every embedded preview loads the shared connection before its renderer; draft scene previews never capture real keys',()=>{for(const file of ['ladder.html','ladder-output.html','cat-keyboard.html','gameframe.html','resource-template.html','scoreboard.html','live-interaction.html']){const html=fs.readFileSync(require.resolve('../public/'+file),'utf8');assert.match(html,/\/preview-connection\.js/);assert.equal(html.indexOf('/preview-connection.js'),html.indexOf('<script src="')+13,file);}assert.match(fs.readFileSync(require.resolve('../public/ladder-output.js'),'utf8'),/preview&&!livePreview\?\{preview:true,respectVisibility:true\}/);});
test('PNG assets and reference reuse validated cache bytes; control and current state remain uncached',async t=>{
 const app=createAssistant({port:0,dataDir:null,sc2Reader:async()=>{throw Error('offline');},intervalMs:60000});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const base='http://127.0.0.1:'+app.server.address().port;
 for(const route of ['/assets/artanis-character-v1.png','/frame-reference.png']){const r=await fetch(base+route),etag=r.headers.get('etag');assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/private, no-cache/);assert.ok(etag);await r.arrayBuffer();const cached=await fetch(base+route,{headers:{'If-None-Match':etag}});assert.equal(cached.status,304);assert.equal((await cached.arrayBuffer()).byteLength,0);const stale=await fetch(base+route,{headers:{'If-None-Match':'W/"stale"'}});assert.equal(stale.status,200);await stale.arrayBuffer();}
 for(const route of ['/','/api/state','/api/control-session']){const r=await fetch(base+route,{headers:{'X-Control-Client':'assistant'}});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');}assert.equal((await fetch(base+'/preview-connection.js')).status,200);
});
