const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawnSync}=require('node:child_process');
const {createReplayStore}=require('../ladder-replays.cjs'),{createReplayWatcher}=require('../replay-watcher.cjs');
const at=Date.parse('2026-10-08T10:00:00Z');
function parsed(opponentRace,result='W',ownRace='Protoss'){const me={toonHandle:'5-S2-1-1',human:true,name:'Me',race:ownRace,selectedRace:'Random',mmr:4000},op={toonHandle:'5-S2-1-2',human:true,name:'Other',race:opponentRace,selectedRace:'Random',mmr:4000};return {ok:true,at,map:'Map',durationSeconds:600,players:[me,op],selfPlayers:[me],opponents:[op],selfResult:result};}
function store(file){let clock=at-10000;const s=createReplayStore(file,()=>clock);clock=at+10000;s.configure({toonHandle:'5-S2-1-1'});return s;}
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'random-race-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('Python parser distinguishes selected random from assigned or details race and retains both fields',()=>{const r=spawnSync(require('../runtime-paths.cjs').python(),['-X','utf8',path.join(__dirname,'random-race-parser-test.py')],{windowsHide:true,encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);assert.match(r.stderr,/Ran 3 tests/);});
test('random opponents count wins and losses under actual race in today and current session',()=>{for(const [full,race]of [['Terran','T'],['Protoss','P'],['Zerg','Z']])for(const result of ['W','L']){const s=store();s.acceptReplay(parsed(full,result),'one');const snap=s.snapshot(),field=result==='W'?'wins':'losses';assert.equal(snap.stats[field],1);assert.equal(snap.session.stats[field],1);assert.equal(snap.stats.matchups[race][field],1);assert.equal(snap.session.stats.matchups[race][field],1);assert.equal(snap.records[0].opponentRace,race);assert.equal(snap.records[0].race,'P');}});
test('re-reading fixes old random labels while preserving totals, manual correction, exclusion and record identity',t=>{
 const file=path.join(temp(t),'records.json'),s=store(file);s.acceptReplay(parsed('Random','W','Random'),'one');const before=s.snapshot(),id=before.records[0].id;s.edit(id,{result:'loss'});const sessionId=before.session.id;
 assert.equal(s.acceptReplay(parsed('Zerg','W','Terran'),'copy').kind,'duplicate');const snap=s.snapshot();assert.equal(snap.records.length,1);assert.equal(snap.records[0].id,id);assert.equal(snap.records[0].result,'loss');assert.equal(snap.records[0].replayResult,'win');assert.equal(snap.records[0].opponentRace,'Z');assert.equal(snap.records[0].race,'T');assert.equal(snap.session.id,sessionId);assert.equal(snap.stats.losses,1);assert.equal(snap.stats.matchups.Z.losses,1);assert.equal(snap.session.stats.matchups.Z.losses,1);
 s.undo();assert.equal(s.acceptReplay(parsed('Protoss','W','Terran'),'one').kind,'duplicate');assert.equal(s.snapshot().stats.total,0);assert.equal(s.snapshot().session.stats.total,0);const restored=store(file);assert.equal(restored.snapshot().records[0].opponentRace,'P');assert.equal(restored.snapshot().records[0].excluded,true);
});
test('unresolved random race cannot overwrite a known race or create a guessed matchup',()=>{const s=store();s.acceptReplay(parsed('Random'),'one');assert.equal(s.snapshot().stats.total,1);assert.deepEqual(s.snapshot().stats.matchups,{T:{wins:0,losses:0},Z:{wins:0,losses:0},P:{wins:0,losses:0}});s.acceptReplay(parsed('Terran'),'one');s.acceptReplay(parsed('Random'),'one');assert.equal(s.snapshot().records[0].opponentRace,'T');assert.equal(s.snapshot().stats.matchups.T.wins,1);});
test('manual rescan repairs a cached random record without adding wins or changing session boundary',async t=>{const dir=temp(t),s=store();s.acceptReplay(parsed('Random'),'hash');s.configure({replayDirectory:dir});const file=path.join(dir,'random.SC2Replay');fs.writeFileSync(file,'fixture');fs.utimesSync(file,new Date(at-5000),new Date(at-5000));const w=createReplayWatcher({store:s,now:()=>at+10000,parser:async()=>parsed('Protoss'),intervalMs:100000});t.after(()=>w.close());const started=s.snapshot().session.startedAt;await w.scan('today');assert.equal(s.snapshot().stats.total,1);assert.equal(s.snapshot().stats.matchups.P.wins,1);assert.equal(s.snapshot().session.stats.matchups.P.wins,1);assert.equal(s.snapshot().session.startedAt,started);await w.scan('recent');assert.equal(s.snapshot().records.length,1);});
test('account display retains random lobby choice while records use the actual race',async t=>{const dir=path.join(temp(t),'StarCraft II','Accounts','123','5-S2-1-1','Replays','Multiplayer');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'random.SC2Replay'),'fixture');const profile=await require('../account-discovery.cjs').inspectAccount({replayDirectory:dir},dir,{documents:[],parser:async()=>parsed('Terran')});assert.equal(profile.race,'R');assert.deepEqual(profile.names,['Me']);});
