const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{once}=require('node:events');
const {createReplayStore}=require('../ladder-replays.cjs'),{createAssistant}=require('../ladder-server.cjs'),{createReplayWatcher,parseReplay}=require('../replay-watcher.cjs');
const at=Date.parse('2026-10-05T12:00:00Z');
function parsed(extra={}){const me={toonHandle:'5-S2-1-9469666',name:'Me',human:true,mmr:4000,race:'Terran'},op={toonHandle:'5-S2-1-7',name:'Other',human:true,mmr:4000,race:'Zerg'};return{ok:true,at,durationSeconds:600,map:'Map',players:[me,op],selfPlayers:[me],opponents:[op],selfResult:'W',...extra};}
function store(file=null){const s=createReplayStore(file,()=>at+10000);s.configure({toonHandle:'5-S2-1-9469666'});return s;}
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'天梯测试-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('repeated events, copied content and semantic match copies count once',()=>{const s=store(),p=parsed();s.acceptReplay(p,'a');s.acceptReplay(p,'a');s.acceptReplay(p,'copy-with-other-hash');assert.equal(s.snapshot().stats.total,1);assert.equal(s.snapshot().stats.matchups.Z.wins,1);});
test('deduplication and exclusions survive restart',t=>{const file=path.join(temp(t),'records.json'),s=store(file);s.acceptReplay(parsed(),'a');s.undo();const restored=createReplayStore(file,()=>at+10000);restored.acceptReplay(parsed(),'a');assert.equal(restored.snapshot().stats.total,0);assert.equal(restored.snapshot().records.length,1);});
test('manual first reconciles with replay without changing a manual correction',()=>{const s=store();s.add('loss');s.acceptReplay(parsed(),'a');assert.equal(s.snapshot().stats.total,1);assert.equal(s.snapshot().stats.losses,1);assert.equal(s.snapshot().records[0].replayResult,'win');assert.equal(s.snapshot().records[0].source,'manual');});
test('automatic first blocks an overlapping manual record',()=>{const s=store();s.acceptReplay(parsed(),'a');assert.throws(()=>s.add('win'),/已有录像/);assert.equal(s.snapshot().stats.total,1);});
test('ambiguous manual candidates remain pending until explicitly linked',()=>{const s=store();s.add('win');s.add('loss');assert.equal(s.acceptReplay(parsed(),'a').kind,'pending');assert.equal(s.snapshot().stats.total,2);const p=s.snapshot().pending[0];s.resolve(p.key,p.candidates[0]);assert.equal(s.snapshot().stats.total,2);assert.equal(s.snapshot().pending.length,0);assert.equal(s.acceptReplay(parsed(),'a').kind,'duplicate');});
test('excluded manual matches cannot be revived by a later replay',()=>{const s=store();s.add('win');s.undo();s.acceptReplay(parsed(),'a');assert.equal(s.snapshot().stats.total,0);assert.equal(s.snapshot().config.mmr,null);});
test('observer, bots, unknown result, teams and ambiguous self are excluded',()=>{for(const p of [parsed({selfPlayers:[],opponents:[]}),parsed({selfResult:null}),parsed({players:[{human:false},{human:true}]}),parsed({players:[{human:true},{human:true},{human:true}]}),parsed({selfPlayers:[{},{}]})]){const s=store();assert.equal(s.acceptReplay(p,'a').kind,'skipped');assert.equal(s.snapshot().stats.total,0);}});
test('invalid and placeholder MMR preserve the display',()=>{for(const value of [0,-1,4294967295,null,'4000',NaN]){const s=store();s.updateMMR(4000);const p=parsed({at:at+20000});p.selfPlayers[0].mmr=value;s.acceptReplay(p,'a');assert.equal(s.snapshot().config.mmr,4000);assert.match(s.snapshot().mmrMessage,/保留/);}});
test('valid replay MMR is labelled and older imports do not roll it back',()=>{const s=store();s.acceptReplay(parsed(),'a');assert.equal(s.snapshot().config.mmrSource,'replay');const p=parsed({at:at-3600000});p.selfPlayers[0].mmr=3500;s.acceptReplay(p,'older');assert.equal(s.snapshot().config.mmr,4000);});
test('estimate is opt-in, uses K44 scale850 and never invents a seed',()=>{const s=store();s.configure({mmrMode:'estimate'});s.acceptReplay(parsed(),'a');assert.equal(s.snapshot().config.mmr,4022);assert.equal(s.snapshot().config.mmrSource,'estimate');assert.match(s.snapshot().mmrMessage,/不是官方/);const b=store();b.configure({mmrMode:'estimate'});const p=parsed();p.selfPlayers[0].mmr=0;b.acceptReplay(p,'a');assert.equal(b.snapshot().config.mmr,null);});
test('manual-only MMR and newer manual values remain unchanged',()=>{const s=store();s.configure({mmrMode:'manual'});s.updateMMR(4500);s.acceptReplay(parsed({at:at+20000}),'a');assert.equal(s.snapshot().config.mmr,4500);const b=store();b.updateMMR(4600);b.acceptReplay(parsed(),'a');assert.equal(b.snapshot().config.mmr,4600);});
test('account switch isolates records and MMR, then restores known account values',()=>{const s=store();s.acceptReplay(parsed(),'a');s.configure({toonHandle:'5-S2-1-7'});assert.equal(s.snapshot().stats.total,0);assert.equal(s.snapshot().config.mmr,null);s.configure({toonHandle:'5-S2-1-9469666'});assert.equal(s.snapshot().stats.total,1);assert.equal(s.snapshot().config.mmr,4000);});
test('Beijing day boundary uses actual replay date and ordered streak',()=>{const s=store();s.acceptReplay(parsed(),'a');s.acceptReplay(parsed({at:at-86400000}),'old');assert.equal(s.snapshot().stats.total,1);s.acceptReplay(parsed({at:at-20000,selfResult:'L'}),'earlier');assert.equal(s.snapshot().stats.streak,'1连胜');});
test('client observations never create results',()=>{const s=store();s.configure({names:['Me']});for(const phase of ['live','menu'])s.observe({phase,game:{isReplay:false,displayTime:100,players:[{name:'Me',type:'user',race:'Terr',result:'Victory'},{name:'Other',type:'user',race:'Zerg'}]}});assert.equal(s.snapshot().stats.total,0);});
test('watcher checks actual replay date, copies, repeated scans and Chinese paths',async t=>{const dir=temp(t),s=store();s.configure({replayDirectory:dir});fs.writeFileSync(path.join(dir,'录像.SC2Replay'),'content');fs.writeFileSync(path.join(dir,'复制.SC2Replay'),'content');const watcher=createReplayWatcher({store:s,now:()=>Date.now()+10000,parser:async()=>parsed(),intervalMs:100000});t.after(()=>watcher.close());await watcher.scan('recent');await watcher.scan('recent');assert.equal(s.snapshot().stats.total,1);assert.equal(watcher.snapshot().duplicates,2);});
test('parser failure is visible and retryable',async t=>{const dir=temp(t),s=store();s.configure({replayDirectory:dir});fs.writeFileSync(path.join(dir,'坏录像.SC2Replay'),'bad');let fail=true;const w=createReplayWatcher({store:s,now:()=>Date.now()+10000,parser:async()=>{if(fail)throw Error('broken');return parsed();},intervalMs:100000});t.after(()=>w.close());await w.scan('recent');assert.equal(w.snapshot().errors.length,1);fail=false;await w.scan('recent');assert.equal(s.snapshot().stats.total,1);});
test('independent service authenticates actions and exposes no tournament routes',async t=>{const app=createAssistant({port:0,dataDir:null,sc2Reader:async()=> 'offline',intervalMs:100000});app.server.listen(0,'127.0.0.1');await once(app.server,'listening');t.after(()=>app.close());const url=`http://127.0.0.1:${app.server.address().port}`;const html=await(await fetch(url)).text();assert.doesNotMatch(html,/赛事导播台|赛事对阵/);const token=html.match(/name="control-token" content="([a-f0-9]+)"/)[1];
  assert.equal((await fetch(url+'/api/action',{method:'POST',body:'{}'})).status,403);assert.equal((await fetch(url+'/bracket')).status,404);
  async function action(data){const r=await fetch(url+'/api/action',{method:'POST',headers:{'X-Control-Token':token},body:JSON.stringify(data)});return{code:r.status,data:await r.json()};}
  assert.equal((await action({action:'bracketFetch',key:'unused'})).code,400);const change=await action({action:'configure',config:{sc2AutoMode:'tournament'}});assert.equal(change.data.config.sc2AutoMode,'ladder');assert.equal((await action({action:'ladderConfigure',config:{toonHandle:'invalid'}})).code,400);
  for(const route of ['/output','/assistant.js','/assistant.css','/ladder-output.js','/ladder-overlay.js','/obs.js'])assert.equal((await fetch(url+route)).status,200);
});
test('public real replay parses result and tracker statistics; identity precedence excludes unrelated accounts',async t=>{
 const fixture=path.join(__dirname,'fixtures','iaguz-luneth-4.7.1.SC2Replay'),bytes=fs.readFileSync(fixture);
 assert.equal(require('node:crypto').createHash('sha256').update(bytes).digest('hex'),'b15a192659ca2145a8e82f96254f6637b778788a2329e900ab712abaccc2d4d7');
 const folder=path.join(temp(t),'5-S2-1-9','Replays','Multiplayer');fs.mkdirSync(folder,{recursive:true});const file=path.join(folder,'公开样本.SC2Replay');fs.copyFileSync(fixture,file);
 const unrelated=await parseReplay(file,{toonHandle:'',names:[],metadataOnly:true});assert.equal(unrelated.selfPlayers.length,0);
 const byName=await parseReplay(file,{toonHandle:'',names:['iaguz']});assert.equal(byName.selfPlayers.length,1);assert.equal(byName.selfPlayers[0].toonHandle,'1-S2-1-4176016');assert.equal(byName.selfResult,'L');assert.equal(byName.durationSeconds,826);assert.equal(byName.dailyMetrics.status,'ready');assert.equal(byName.dailyMetrics.zerglings,4);assert.equal(byName.dailyMetrics.workersKilled,12);
 const byHandle=await parseReplay(file,{toonHandle:'5-S2-1-9',names:['iaguz'],metadataOnly:true});assert.equal(byHandle.selfPlayers.length,0);
});
test('independent automation runs without a control browser and manual changes pause it',async t=>{let phase='menu',time=0;const app=createAssistant({port:0,dataDir:null,now:()=>time,sc2Reader:async()=>phase,intervalMs:100000});t.after(()=>app.close());app.server.listen(0,'127.0.0.1');await once(app.server,'listening');const base=`http://127.0.0.1:${app.server.address().port}`,html=await(await fetch(base)).text(),token=html.match(/content="([a-f0-9]{48})"/)[1];async function act(data){const r=await fetch(base+'/api/action',{method:'POST',headers:{'X-Control-Token':token},body:JSON.stringify(data)});return r.json();}await act({action:'configure',config:{sc2AutoEnabled:true,sc2StartDelay:0,sc2EndDelay:0}});await app.sc2.poll();phase='live';await app.sc2.poll();time=1000;await app.sc2.poll();assert.equal(app.snapshot().scene,'game');phase='offline';await app.sc2.poll();assert.equal(app.snapshot().scene,'game');await act({action:'transition',scene:'intermission'});assert.equal(app.snapshot().config.sc2AutoPaused,true);phase='live';await app.sc2.poll();await app.sc2.poll();assert.equal(app.snapshot().scene,'intermission');assert.equal(app.snapshot().ladder.stats.total,0);});
test('today watcher uses replay date even when yesterday replay was copied today, and idle checks retain diagnostics',async t=>{const dir=temp(t),s=store();s.configure({replayDirectory:dir});fs.writeFileSync(path.join(dir,'复制旧录像.SC2Replay'),'old');const clock=()=>at+10000;fs.utimesSync(path.join(dir,'复制旧录像.SC2Replay'),new Date(at-5000),new Date(at-5000));const w=createReplayWatcher({store:s,now:clock,parser:async()=>parsed({at:at-86400000}),intervalMs:100000});t.after(()=>w.close());await w.scan('today');assert.equal(s.snapshot().stats.total,0);const message=w.snapshot().message;await w.scan('auto');assert.equal(w.snapshot().message,message);});
test('stale sessions after restart do not block or mislabel a new manual record',t=>{const file=path.join(temp(t),'records.json');let time=at;const s=createReplayStore(file,()=>time);s.configure({toonHandle:'5-S2-1-9469666',names:['Me']});s.observe({phase:'live',game:{isReplay:false,displayTime:500,players:[{name:'Me',type:'user',race:'Terr'},{name:'Old opponent',type:'user',race:'Zerg'}]}});s.add('win');time+=86400000;const restored=createReplayStore(file,()=>time);restored.add('loss');assert.equal(restored.snapshot().records[0].opponent,'手动记录');assert.equal(restored.snapshot().stats.losses,1);});

test('short replay ignores unrelated undone manual tests before its actual start and repairs old pending on rescan',t=>{
 const file=path.join(temp(t),'records.json'),s=store(file);s.add('loss',{at:at-100000});s.add('win',{at:at-99000});s.undo();s.undo();
 const saved=JSON.parse(fs.readFileSync(file,'utf8')),p=parsed({durationSeconds:14,selfResult:'L'});
 const crypto=require('node:crypto'),match=crypto.createHash('sha256').update(JSON.stringify([p.at,p.durationSeconds,p.map,p.players.map(x=>x.toonHandle).sort()])).digest('hex'),key=s.getConfig().toonHandle+':'+match;
 saved.pending[key]={key,hash:'short',parsed:p,identity:s.getConfig().toonHandle,candidates:saved.records.map(r=>r.id)};fs.writeFileSync(file,JSON.stringify(saved));
 const restored=store(file);assert.equal(restored.acceptReplay(p,'short').kind,'recorded');assert.equal(restored.snapshot().stats.losses,1);assert.equal(restored.snapshot().stats.wins,0);assert.equal(restored.snapshot().pending.length,0);assert.equal(restored.snapshot().records.filter(r=>r.excluded).length,2);assert.equal(restored.acceptReplay(p,'copy').kind,'duplicate');
});
test('excluded actual short-match manual correction remains excluded and is linked once',()=>{const s=store();s.add('win',{at:at+1000});s.undo();assert.equal(s.acceptReplay(parsed({durationSeconds:14}),'short').kind,'recorded');assert.equal(s.snapshot().stats.total,0);assert.equal(s.snapshot().records.length,1);});
