const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm');
const R=require('../public/resource-template.js'),S=require('../public/scene-customization.js'),packs=require('../public/outfit-presets.js'),{defaults,sanitize,createReplayStore}=require('../ladder-replays.cjs'),{createAssistant}=require('../ladder-server.cjs');
test('resource templates protect number windows even at extreme positions and large artwork',()=>{for(const style of Object.keys(R.themes)){const svg=R.build({...R.defaults,resourceStyle:style,resourceMineralX:1530,resourceVespeneX:1670,resourceSupplyX:1800,resourceIconScale:150});assert.match(svg,/maskUnits="userSpaceOnUse"/);for(const a of R.numberAreas)assert.ok(svg.includes(`x="${a.x}" y="${a.y}" width="${a.w}" height="${a.h}" fill="black"`));assert.equal((svg.match(/data-resource-slot=/g)||[]).length,3);assert.match(svg,new RegExp('/assets/resource-'+style+'-v1.png'));assert.doesNotMatch(svg,/<text|foreignObject/);}});
test('resource configuration persists, is independent of dressing, and rejects unsafe values',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sc2-resource-'));try{const file=path.join(dir,'records.json'),store=createReplayStore(file);store.configure({resourceEnabled:true,resourceStyle:'vesna',resourceIconScale:135,resourceY:12,resourceBackdropStyle:'glow'});store.flush();const c=createReplayStore(file).getConfig();assert.equal(c.resourceEnabled,true);assert.equal(c.resourceStyle,'vesna');assert.equal(c.resourceIconScale,135);assert.equal(c.resourceBackdropStyle,'glow');const p=packs.buildPatch(c,{preset:'protoss'}),next=sanitize(p,c);for(const k of R.fields)assert.deepEqual(next[k],c[k]);for(const bad of [{resourceStyle:'__proto__'},{resourceStyle:'<script>'},{resourceEnabled:1},{resourceMineralX:NaN},{resourceY:101},{resourceOpacity:0},{resourceIconScale:201},{resourceBackdrop:'red" onload="x'},{resourceBackdropStyle:'url(evil)'}])assert.throws(()=>sanitize(bad));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('resource layer obeys game, replay-game, waiting and blank visibility without reading game numbers',()=>{const box={hidden:true,innerHTML:''},context={document:{getElementById:()=>box,body:{dataset:{}}},window:{ResourceTemplate:R,SceneCustomization:S}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../public/resource-overlay.js'),'utf8'),context);for(const [scene,enabled,global,show,expected]of [['game',true,true,true,true],['game',false,true,true,false],['game',true,false,true,false],['intermission',true,true,false,false],['custom',true,true,true,true],['blank',true,true,true,false]]){const prefix=S.prefixes[scene],c={...defaults,resourceEnabled:enabled,enabled:global,[prefix+'ShowResources']:show};context.window.ResourceOverlay.render({scene,ladder:{config:c}});assert.equal(!box.hidden,expected,scene);}assert.ok(S.fields('game').includes('resourceStyle'));assert.ok(S.fields('custom').includes('customShowResources'));});
test('every resource asset and output route is usable, standalone has no private reference in production',async t=>{const app=createAssistant({port:0,dataDir:null,sc2Reader:async()=>{throw Error('offline');},intervalMs:60000});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const base='http://127.0.0.1:'+app.server.address().port;for(const route of ['/resource-template','/resource-template.js','/resource-template.css','/resource-overlay.js','/resource-workspace.js',...Object.keys(R.themes).map(id=>'/assets/resource-'+id+'-v1.png')])assert.equal((await fetch(base+route)).status,200,route);for(const id of Object.keys(R.themes)){const b=fs.readFileSync(path.join(__dirname,'../public/assets/resource-'+id+'-v1.png'));assert.equal(b[25],6);assert.equal(b.readUInt32BE(16),b.readUInt32BE(20)*3);}const html=await(await fetch(base)).text();assert.match(html,/data-view="resources"/);assert.match(html,/mainResourceEnabled/);const output=await(await fetch(base+'/output')).text();assert.match(output,/resourceWidget/);assert.doesNotMatch(await(await fetch(base+'/resource-template')).text(),/src="\/frame-reference.png"/);assert.equal(app.ladder.getConfig().resourceEnabled,false);});

test('larger resource icons expand left of each number window instead of clipping into the old small tile',()=>{
 const small=R.build({...R.defaults,resourceIconScale:100}),large=R.build({...R.defaults,resourceIconScale:200});
 function slots(svg){return [...svg.matchAll(/data-resource-slot="([^"]+)" x="([^"]+)" y="([^"]+)" width="([^"]+)" height="([^"]+)"/g)].map(m=>({key:m[1],x:+m[2],y:+m[3],w:+m[4],h:+m[5]}));}
 const a=slots(small),b=slots(large);assert.equal(b.length,3);
 for(let i=0;i<3;i++){assert.equal(b[i].w,a[i].w*2);assert.equal(b[i].h,a[i].h*2);assert.equal(b[i].x+b[i].w,a[i].x+a[i].w);assert.ok(b[i].x+b[i].w<R.numberAreas[i].x);assert.ok(b[i].y>=0);}
 assert.equal(R.defaults.resourceIconScale,140);
});
test('transparent resource icons have no backdrop; glow fades completely and solid cover stays optional',()=>{
 assert.equal(R.defaults.resourceBackdropStyle,'transparent');
 assert.doesNotMatch(R.build(R.defaults),/data-resource-backdrop=/);
 const glow=R.build({...R.defaults,resourceBackdropStyle:'glow'});assert.match(glow,/data-resource-backdrop="glow"/);assert.match(glow,/offset="1"[^>]+stop-opacity="0"/);assert.doesNotMatch(glow,/data-resource-backdrop="solid"/);
 assert.match(R.build({...R.defaults,resourceBackdropStyle:'solid',resourceBackdrop:'#123456'}),/data-resource-backdrop="solid"[^>]+fill="#123456"/);
 assert.ok(S.fields('game').includes('resourceBackdropStyle'));
});
test('decoration tools share their category and keyboard keeps an independent sidebar entry',()=>{
 const html=fs.readFileSync(require.resolve('../public/ladder.html'),'utf8');
 assert.match(html,/data-route="catkeyboard"/);assert.doesNotMatch(html,/data-route="resources"/);assert.match(html,/data-route="appearance"[^>]*>.*?<span>画面装饰<\/span>/s);
 assert.equal((html.match(/aria-label="画面装饰功能"/g)||[]).length,3);assert.match(html,/href="#resources" aria-current="page">资源模板/);
 assert.match(html,/id="resourceBackdropStyle"/);assert.match(html,/id="resourceIconScale"[^>]+max="200"/);
});
