const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const {createReplayStore,sanitize,defaults}=require('../ladder-replays.cjs'),{createAssistant}=require('../ladder-server.cjs'),themes=require('../public/scene-themes.js'),cat=require('../public/cat-keyboard-template.js'),frame=require('../public/gameframe-template.js');
const read=file=>fs.readFileSync(path.join(__dirname,'../public',file),'utf8');
test('Nahida assistant and both scene presets persist independently and retain the matching console frame',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'nahida-config-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'records.json'),store=createReplayStore(file);
 store.configure({catCharacter:'nahida',catView:'rear',catKeyboardSide:'right',waitingTheme:'nahida',breakTheme:'vesna',gameFrameStyle:'nahida'});
 const saved=createReplayStore(file);assert.equal(saved.getConfig().catCharacter,'nahida');assert.equal(saved.getConfig().waitingTheme,'nahida');assert.equal(saved.getConfig().breakTheme,'vesna');saved.configure({breakTheme:'nahida'});assert.equal(createReplayStore(file).getConfig().breakTheme,'nahida');assert.equal(saved.getConfig().waitingTheme,'nahida');assert.equal(saved.getConfig().gameFrameStyle,'nahida');
 assert.match(themes.decoration(themes.resolve(saved.getConfig(),'break')),/scene-character-nahida/);assert.equal(themes.presets.nahida.Layout,'left');assert.match(cat.build(saved.getConfig()),/纳西妲/);
});
test('waiting and away have independent persisted themes, text and media with strict validation',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'scene-config-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'records.json'),store=createReplayStore(file),video='/scene-media/'+'b'.repeat(64)+'.webm';
 store.add('win');store.configure({waitingTheme:'starcraft',waitingTitle:'等待对手',breakTheme:'vesna',breakTitle:'马上回来',breakBackground:'video',breakBackgroundVideo:video,breakVideoMuted:false,breakShowText:false,catCharacter:'naiwa',catCurve:false,gameFrameStyle:'nahida'});
 const c=createReplayStore(file).snapshot();assert.equal(c.config.waitingTheme,'starcraft');assert.equal(c.config.breakTheme,'vesna');assert.equal(c.config.breakBackgroundVideo,video);assert.equal(c.config.breakVideoMuted,false);assert.equal(c.config.catCharacter,'naiwa');assert.equal(c.config.catCurve,false);assert.equal(c.config.gameFrameStyle,'nahida');assert.equal(c.stats.wins,1);
 const resolved=themes.resolve(c.config,'break');assert.equal(resolved.waitingTitle,'马上回来');assert.equal(resolved.waitingBackgroundVideo,video);assert.equal(c.config.waitingTitle,'等待对手');assert.equal(themes.resolve(c.config,'intermission'),c.config);
 for(const bad of [{breakTheme:'../x'},{breakShowText:1},{breakVideoMuted:'false'},{breakTitle:'x'.repeat(61)},{breakBackgroundVideo:'https://example.com/a.mp4'},{waitingBackgroundVideo:'/scene-media/../records.json'},{breakDim:-1},{catCharacter:'unknown'},{catCurve:1}])assert.throws(()=>sanitize(bad));
});
test('new assistant skins preserve one half keyboard and front/rear poses; frames crop one character and keep panel interiors clear',()=>{
 for(const character of ['vesna','naiwa','nahida'])for(const side of ['left','right']){const html=cat.build({catCharacter:character,catView:'rear',catKeyboardSide:side});assert.match(html,new RegExp('cat-character-'+character));assert.equal((html.match(/class="cat-board"/g)||[]).length,1);assert.doesNotMatch(html,/cat-touchboard/);assert.match(html,/cat-curved/);assert.doesNotMatch(cat.build({catCharacter:character,catCurve:false}),/cat-curved/);const png=fs.readFileSync(path.join(__dirname,'../public/assets',character+'-keys-v1.png'));assert.equal(png.readUInt32BE(16),1536);assert.equal(png.readUInt32BE(20),1024);assert.equal(png[25],6);}
 for(const style of ['naiwa','nahida','vesna']){const svg=frame.build({...defaults,gameFrameStyle:style});assert.match(svg,new RegExp('data-frame-theme="'+style+'"'));assert.match(svg,/<image href=/);for(const group of svg.matchAll(/<g data-panel="[^"]+">(.*?)<\/g>/g)){const paths=[...group[1].matchAll(/<path[^>]+>/g)];assert.match(paths[0][0],/fill="none"/);assert.match(paths[1][0],/fill="none"/);}assert.doesNotMatch(frame.build({...defaults,gameFrameStyle:style,gameFrameDecorations:false}),/<image|data-decoration=/);if(style!=='nahida')assert.match(svg,/viewBox="0 0 512 512" overflow="hidden"/);}
 assert.match(themes.decoration({waitingTheme:'team',waitingTeamName:'<img src=x>'}),/&lt;img src=x&gt;/);
});
test('scene video plays only visible media, applies loop and mute, and unloads when entering a game',async()=>{
 const video={hidden:true,style:{},listeners:{},playCalls:0,pauseCalls:0,loadCalls:0,addEventListener(k,f){this.listeners[k]=f;},play(){this.playCalls++;return Promise.resolve();},pause(){this.pauseCalls++;},load(){this.loadCalls++;},removeAttribute(k){delete this[k];}},win={};
 vm.runInNewContext(read('scene-video.js'),{window:win,document:{getElementById:()=>video,body:{classList:{contains:()=>false}}}});
 const c={waitingBackground:'video',waitingBackgroundVideo:'/scene-media/a.webm',waitingVideoMuted:true,waitingVideoLoop:true,waitingImageFit:'contain'};win.SceneVideo.render(c,false);assert.equal(video.hidden,false);assert.equal(video.playCalls,1);assert.equal(video.muted,true);assert.equal(video.loop,true);assert.equal(video.style.objectFit,'contain');win.SceneVideo.render(c,false);assert.equal(video.playCalls,1,'status refresh does not restart playback');win.SceneVideo.render({...c,waitingVideoMuted:false,waitingVideoLoop:false},false);assert.equal(video.muted,false);assert.equal(video.loop,false);win.SceneVideo.render(c,true);assert.equal(video.hidden,true);assert.equal(video.pauseCalls,1);assert.equal(video.src,undefined);win.SceneVideo.render(c,false);assert.equal(video.playCalls,2);video.listeners.error();assert.equal(video.hidden,true);
});
test('away renderer resolves its own title and hides all media and theme decorations in game',()=>{
 const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:false,textContent:'',innerHTML:'',style:{setProperty(k,v){this[k]=v;}},parentElement:{hidden:false},getAttribute(){return '';}});return nodes.get(id);},calls=[],win={SceneThemes:themes,SceneVideo:{render:(c,hidden)=>calls.push({c,hidden})}};
 vm.runInNewContext(read('ladder-overlay.js'),{window:win,document:{getElementById:node}});const store=createReplayStore();store.configure({breakTheme:'vesna',breakTitle:'暂离独立标题',waitingTitle:'等待独立标题',breakShowText:false,waitingShowHUD:true});const state={scene:'break',ladder:store.snapshot()};win.LadderOverlay.render(state);assert.equal(node('waitingTitle').textContent,'暂离独立标题');assert.equal(node('waitingInner').hidden,true);assert.equal(node('waitingDecoration').hidden,true);assert.equal(node('ladderHUD').hidden,true);assert.equal(calls.at(-1).hidden,false);state.scene='game';win.LadderOverlay.render(state);assert.equal(node('ladderWaiting').hidden,true);assert.equal(calls.at(-1).hidden,true);state.scene='intermission';win.LadderOverlay.render(state);assert.equal(node('waitingTitle').textContent,'等待独立标题');assert.equal(node('waitingInner').hidden,false);
});
test('away drafts never alter waiting or saved output; dedicated sources remain on the chosen scene',()=>{
 function harness(search,pathname='/output'){let events;const listeners={},renders=[],parent={};vm.runInNewContext(read('ladder-output.js'),{location:{search,pathname,origin:'http://localhost:1'},parent,URLSearchParams,innerWidth:1920,innerHeight:1080,document:{body:{classList:{add(){}}},getElementById:()=>({style:{},hidden:false})},addEventListener:(k,f)=>listeners[k]=f,window:{LadderOverlay:{render:s=>renders.push(s)},ScoreboardOverlay:{render(){}}},EventSource:class{constructor(){events=this;}}});return{events,listeners,renders,parent};}
 const saved={scene:'game',ladder:createReplayStore().snapshot()},h=harness('?preview=1&phase=break&module=break');h.events.onmessage({data:JSON.stringify(saved)});h.listeners.message({origin:'http://localhost:1',source:h.parent,data:{type:'waitingDraft',config:{breakTitle:'暂离草稿',waitingTitle:'不应覆盖',catEnabled:true}}});assert.equal(h.renders.at(-1).scene,'break');assert.equal(h.renders.at(-1).ladder.config.breakTitle,'暂离草稿');assert.equal(h.renders.at(-1).ladder.config.waitingTitle,saved.ladder.config.waitingTitle);assert.equal(h.renders.at(-1).ladder.config.catEnabled,false);
 for(const [url,scene]of [['/waiting-screen','intermission'],['/away-screen','break']]){const o=harness('',url);o.events.onmessage({data:JSON.stringify(saved)});assert.equal(o.renders.at(-1).scene,scene);assert.equal(o.listeners.message,undefined);}
});
test('media upload is authenticated, stays a draft until applied, survives restart and supports video byte ranges and new SVG exports',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'scene-media-')),app=createAssistant({port:0,dataDir:dir,sc2Reader:async()=>{throw Error('offline');},intervalMs:60000});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>{app.close();fs.rmSync(dir,{recursive:true,force:true});});const root='http://127.0.0.1:'+app.server.address().port,html=await(await fetch(root)).text(),token=html.match(/name="control-token" content="([^"]+)"/)[1],post=(body,headers={})=>fetch(root+'/api/scene-media',{method:'POST',headers,body});
 assert.equal((await post('bad')).status,403);assert.equal((await post('bad',{'X-Control-Token':token,Origin:'https://example.com'})).status,403);assert.equal((await post('<svg/>',{'X-Control-Token':token})).status,400);assert.equal(fs.readdirSync(path.join(dir,'media')).filter(f=>f.startsWith('.upload')).length,0);
 const bytes=Buffer.concat([Buffer.from('000000186674797069736f6d0000020069736f6d6d703432','hex'),Buffer.from('range-test-content')]),response=await post(bytes,{'X-Control-Token':token});assert.equal(response.status,200);const media=await response.json();assert.equal(media.kind,'video');assert.equal(app.ladder.getConfig().breakBackgroundVideo,'');
 const whole=await fetch(root+media.url);assert.equal(whole.headers.get('content-type'),'video/mp4');assert.deepEqual(Buffer.from(await whole.arrayBuffer()),bytes);const ranged=await fetch(root+media.url,{headers:{Range:'bytes=4-11'}});assert.equal(ranged.status,206);assert.equal(ranged.headers.get('content-range'),`bytes 4-11/${bytes.length}`);assert.deepEqual(Buffer.from(await ranged.arrayBuffer()),bytes.subarray(4,12));const tail=await fetch(root+media.url,{headers:{Range:'bytes=-5'}});assert.deepEqual(Buffer.from(await tail.arrayBuffer()),bytes.subarray(-5));assert.equal((await fetch(root+media.url,{headers:{Range:'bytes=999999-'}})).status,416);assert.equal((await fetch(root+media.url,{method:'HEAD'})).headers.get('content-length'),String(bytes.length));
 const saved=await fetch(root+'/api/action',{method:'POST',headers:{'X-Control-Token':token,'Content-Type':'application/json'},body:JSON.stringify({action:'ladderConfigure',config:{breakBackground:'video',breakBackgroundVideo:media.url}})});assert.equal(saved.status,200);assert.equal(createReplayStore(path.join(dir,'records.json')).getConfig().breakBackgroundVideo,media.url);
 for(const route of ['/waiting-screen','/away-screen','/scene-workspace.js','/scene-video.js','/scene-themes.js','/scene-themes.css','/assets/starcraft-scene-v1.png','/assets/nahida-keys-v1.png'])assert.equal((await fetch(root+route)).status,200,route);
 for(const style of ['naiwa','nahida','vesna']){app.ladder.configure({gameFrameStyle:style});const svg=await(await fetch(root+'/gameframe.svg')).text();assert.match(svg,/href="data:image\/png;base64,/);assert.doesNotMatch(svg,/href="\/assets/);}
});
