const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {AutomationEngine,readClientDetails}=require('../sc2.cjs'),{createAssistant,sanitize}=require('../ladder-server.cjs'),{createReplayStore}=require('../ladder-replays.cjs'),M=require('../public/scene-customization.js'),T=require('../public/cat-keyboard-template.js'),themes=require('../public/scene-themes.js');
test('Automatic scene switching is on by default, covers loading and menus immediately, respects exit delay and manual pause',()=>{
 const c=sanitize({}),e=new AutomationEngine();assert.equal(c.sc2AutoEnabled,true);assert.equal(e.step('loading',c,'intermission',false,0).target,'loading');assert.equal(e.step('live',c,'loading',false,100).target,null);assert.equal(e.step('live',c,'loading',false,200).target,'game');assert.equal(e.step('menu',c,'game',false,300).target,'intermission');assert.equal(e.step('loading',{...c,sc2AutoPaused:true},'break',false,400).target,null);
 const d=new AutomationEngine();assert.equal(d.step('menu',{...c,sc2EndDelay:0.3},'game',false,0).target,null);assert.equal(d.step('menu',{...c,sc2EndDelay:0.3},'game',false,300).target,'intermission');
});
test('A valid menu/loading response does not wait for or require the stale game endpoint',async t=>{
 const original=global.fetch;t.after(()=>global.fetch=original);const calls=[];let screen='ScreenHome/ScreenHome';global.fetch=async url=>{calls.push(url);if(!url.endsWith('/ui'))throw Error('Game endpoint must not be queried');return new Response(JSON.stringify({activeScreens:[screen,'ScreenNavigationSC2/ScreenNavigationSC2']}));};
 assert.equal((await readClientDetails(6119)).phase,'menu');assert.deepEqual(calls,['http://127.0.0.1:6119/ui']);calls.length=0;screen='ScreenLoading/ScreenLoading';assert.equal((await readClientDetails(6119)).phase,'loading');assert.equal(calls.length,1);
});
test('Loading content and scene visibility persist independently; unsafe scene settings are rejected',t=>{
 const os=require('node:os'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'scene-edit-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'records.json'),store=createReplayStore(file);store.configure({loadingTitle:'载入自定义',loadingShowZealots:true,waitingShowZealots:false,gameShowKeyboard:false,breakShowGifts:false,loadingFreePosition:true,loadingTextX:400,loadingTextY:120});const c=createReplayStore(file).getConfig();assert.equal(c.loadingTitle,'载入自定义');assert.equal(c.loadingShowZealots,true);assert.equal(c.waitingShowZealots,false);assert.equal(M.allowed(c,'game','Keyboard'),false);assert.equal(M.allowed(c,'loading','Keyboard'),false);assert.equal(M.allowed(c,'break','Gifts'),false);assert.equal(M.allowed(c,'blank','Gifts',true),false);const loading=themes.resolve(c,'loading');assert.equal(loading.waitingTitle,'载入自定义');assert.equal(loading.waitingTextX,400);for(const bad of [{gameShowKeyboard:'true'},{loadingTextX:-1},{loadingTextY:1001},{loadingBackgroundImage:'https://evil.example/x.png'}])assert.throws(()=>store.configure(bad));
});
test('Flat keyboard contains exactly one half keyboard, no avatar or touch board, and preserves exact key/mouse mapping',()=>{
 for(const side of ['left','right']){const html=T.build({catView:'flat',catKeyboardSide:side,catCharacter:'nahida'});assert.match(html,/cat-flat/);assert.doesNotMatch(html,/cat-avatar|cat-touchboard|cat-curved/);assert.equal((html.match(/class="cat-board"/g)||[]).length,1);for(const row of T.halfRows[side])for(const [id]of row)assert.ok(html.includes('data-cat-key="'+id+'"'));assert.match(html,/data-cat-key="Mouse1"/);}
 let now=0;const m=T.createModel({now:()=>now});m.ingest({sequence:1,status:'active',pressed:['CtrlLeft','Q','Mouse2']},{catView:'flat'});assert.deepEqual(m.snapshot().pressed,['CtrlLeft','Q','Mouse2']);
});
test('Editor drafts stay local, retain chosen loading phase across live updates, and reject account edits and foreign messages',()=>{
 let events;const listeners=[],listener=e=>{for(const fn of listeners)fn(e);};const states=[],parent={},nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:false,style:{}});return nodes.get(id);},win={SceneCustomization:M,LuxuryConsole:require('../public/luxury-console.js'),LadderOverlay:{render:s=>states.push(s)},ScoreboardOverlay:{render(){}},GameFrameOverlay:{render(){}},CatKeyboardOverlay:{render(){}},DailyOverlay:{render(){}}};
 vm.runInNewContext(require('./preview-fixture.cjs')+fs.readFileSync(require.resolve('../public/ladder-output.js'),'utf8'),{window:win,parent,document:{body:{classList:{add(){}}},createElement:()=>({style:{}}),getElementById:id=>{const el=node(id);el.insertBefore=()=>{};return el;}},location:{search:'?preview=1&module=editor&phase=game',origin:'http://localhost:1',pathname:'/output'},URLSearchParams,innerWidth:1920,innerHeight:1080,addEventListener:(type,fn)=>{if(type==='message')listeners.push(fn);},EventSource:class{constructor(){events=this;}}});const saved={scene:'game',ladder:createReplayStore().snapshot()};events.onmessage({data:JSON.stringify(saved)});const send=(source=parent,origin='http://localhost:1')=>listener({source,origin,data:{type:'editorDraft',phase:'loading',config:{loadingTitle:'只在预览',toonHandle:'5-S2-1-999',names:['forged'],enabled:true}}});send();assert.equal(states.at(-1).scene,'loading');assert.equal(states.at(-1).ladder.config.loadingTitle,'只在预览');assert.equal(states.at(-1).ladder.config.toonHandle,'');assert.equal(saved.ladder.config.loadingTitle,'正在载入下一场');events.onmessage({data:JSON.stringify({...saved,scene:'break'})});assert.equal(states.at(-1).scene,'loading');send({},'http://evil.example');assert.equal(states.at(-1).ladder.config.loadingTitle,'只在预览');
});
test('Scene editor controls preserve a draft across live updates, never cut scenes, and apply only selected cosmetic content',async()=>{
 const nodes=new Map(),calls=[],messages=[];let builds=0;function node(id=''){const e={id,type:'',value:'',checked:false,dataset:{},style:{},children:[],append(...items){this.children.push(...items);},replaceChildren(){this.children=[];if(this.id==='sceneEditorFields')builds++;},addEventListener(k,f){this[k]=f;},setAttribute(){},contentWindow:{postMessage:m=>messages.push(m)}};if(id)nodes.set(id,e);return e;}const get=id=>nodes.get(id)||node(id),buttons=M.phases.map(phase=>{const e=node();e.dataset.editScene=phase;return e;}),store=createReplayStore(),state={scene:'game',ladder:store.snapshot()},win={SceneCustomization:M,ResourceTemplate:require('../public/resource-template.js'),SceneThemes:themes,AssistantActions:{toast(){},async act(action,input){calls.push({action,...input});store.configure(input.config);return{...state,ladder:store.snapshot()};}}};let message;
 vm.runInNewContext(fs.readFileSync(require.resolve('../public/scene-editor.js'),'utf8'),{window:win,document:{getElementById:get,createElement:()=>node(),querySelectorAll:()=>buttons},location:{origin:'http://localhost:1'},addEventListener:(type,fn)=>message=fn});win.SceneEditor.render(state);win.SceneEditor.connection(true);const before=builds;win.SceneEditor.render({...state,serverNow:123});assert.equal(builds,before,'Stable config must not recreate focused controls');buttons[1].click();assert.equal(calls.length,0);assert.equal(messages.filter(m=>m.type==='editorDraft').at(-1).phase,'loading');const el=node();el.dataset.sceneField='loadingTitle';el.value='测试载入';get('sceneEditorForm').input({target:el});win.SceneEditor.render({...state,scene:'intermission'});assert.equal(messages.filter(m=>m.type==='editorDraft').at(-1).config.loadingTitle,'测试载入');await get('sceneEditorForm').submit({preventDefault(){}});assert.equal(calls.length,1);assert.equal(calls[0].action,'ladderConfigure');assert.deepEqual(JSON.parse(JSON.stringify(calls[0].config)),{loadingTitle:'测试载入'});assert.equal(state.scene,'game');
});
test('Scene editor and loading routes are served, manual loading switch is authenticated, and setting it pauses automation',async t=>{
 const app=createAssistant({port:0,dataDir:null,sc2Reader:async()=> 'offline',intervalMs:60000});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const base='http://127.0.0.1:'+app.server.address().port,html=await(await fetch(base)).text(),token=html.match(/name="control-token" content="([a-f\d]+)"/)[1];assert.match(html,/data-view="scenes"/);assert.match(html,/id="loadingScene"/);for(const url of ['/loading-screen','/scene-customization.js','/scene-editor.js','/scene-editor.css','/scene-editor-preview.js'])assert.equal((await fetch(base+url)).status,200,url);const data={action:'cut',scene:'loading'};assert.equal((await fetch(base+'/api/action',{method:'POST',body:JSON.stringify(data)})).status,403);const response=await fetch(base+'/api/action',{method:'POST',headers:{'X-Control-Token':token},body:JSON.stringify(data)});assert.equal(response.status,200);const next=await response.json();assert.equal(next.scene,'loading');assert.equal(next.config.sc2AutoPaused,true);
});
