const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const {createReplayStore}=require('../ladder-replays.cjs'),ControlConnection=require('../public/control-connection.js');
test('automatic scene button re-enables automation and manual buttons reflect the active mode',async()=>{
 const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',textContent:'',checked:false,style:{},dataset:{},attrs:{},classList:{toggle(){}},addEventListener(type,fn){this[type]=fn;},replaceChildren(){},append(){},setAttribute(k,v){this.attrs[k]=v;}});return nodes.get(id);};
 const buttons=['game','intermission','custom'].map(phase=>{const b=node('phase-'+phase);b.dataset.phase=phase;return b;});
 const state={serverInstanceId:'test-server',config:{sc2AutoEnabled:false,sc2AutoPaused:true,sc2AutoMode:'ladder',sc2StartDelay:0,sc2EndDelay:0,obsMapping:{}},scene:'game',ladder:createReplayStore().snapshot(),automation:{},replays:{busy:false,message:'ready',errors:[],recent:[]}};
 state.ladder.config.enabled=false;let events;const submitted=[];
 vm.runInNewContext(fs.readFileSync(require.resolve('../public/ladder-ui.js'),'utf8'),{window:{ControlConnection},document:{getElementById:node,querySelector:s=>s.startsWith('meta')?{content:'token'}:null,querySelectorAll:s=>s==='[data-phase]'?buttons:[],createElement:()=>node('new')},ObsConnection:class{constructor(){this.ready=false;}},EventSource:class{constructor(){events=this;}},fetch:async(url,options)=>{if(url==='/api/control-session')return{ok:true,json:async()=>({token:'a'.repeat(48),serverInstanceId:state.serverInstanceId})};const request=JSON.parse(options.body);submitted.push(request);if(request.action==='configure')Object.assign(state.config,request.config);if(request.action==='ladderConfigure')Object.assign(state.ladder.config,request.config);if(request.action==='transition'){state.scene=request.scene;state.config.sc2AutoPaused=true;}return{ok:true,json:async()=>state};},location:{origin:'http://127.0.0.1:17864'},console,setTimeout:()=>0,clearTimeout(){},URL,Blob});
 events.onopen();events.onmessage({data:JSON.stringify(state)});await new Promise(setImmediate);
 assert.equal(node('resumeAuto').attrs['aria-pressed'],'false');assert.equal(buttons[0].attrs['aria-pressed'],'true');
 await node('resumeAuto').click();assert.deepEqual(submitted.slice(-2),[{action:'ladderConfigure',config:{enabled:true}},{action:'configure',config:{sc2AutoEnabled:true,sc2AutoPaused:false,sc2AutoMode:'ladder'}}]);assert.equal(node('resumeAuto').attrs['aria-pressed'],'true');assert.ok(buttons.every(b=>b.attrs['aria-pressed']==='false'));
 await buttons[2].click();assert.equal(state.scene,'custom');assert.equal(node('resumeAuto').attrs['aria-pressed'],'false');assert.equal(buttons[2].attrs['aria-pressed'],'true');
 await node('resumeAuto').click();assert.equal(node('resumeAuto').attrs['aria-pressed'],'true');assert.ok(buttons.every(b=>b.attrs['aria-pressed']==='false'));assert.equal(state.ladder.session.stats.total,0);
});
