const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const packs=require('../public/outfit-presets.js'),{createReplayStore,sanitize}=require('../ladder-replays.cjs'),{createCombinationStore}=require('../outfit-combinations.cjs'),{createAssistant}=require('../ladder-server.cjs');
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'组合与等待-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('Full suite replaces both old background modes by default and optionally retains personal media',()=>{
 const store=createReplayStore();store.configure({waitingTheme:'nicole',waitingBackground:'image',waitingBackgroundImage:'/assets/nicole-waiting-v1.png',breakBackground:'video',breakBackgroundVideo:'/scene-media/'+'f'.repeat(64)+'.mp4'});let patch=packs.buildPatch(store.getConfig(),{preset:'nahida'});assert.equal(patch.waitingBackground,'gradient');assert.equal(patch.breakBackground,'gradient');assert.equal(patch.waitingTheme,'nahida');assert.equal(patch.breakTheme,'nahida');assert.equal(patch.waitingBackgroundImage,undefined);store.configure(patch);
 patch=packs.buildPatch(store.getConfig(),{preset:'nicole'});assert.equal(patch.waitingBackgroundImage,'/assets/nicole-waiting-v1.png');assert.equal(patch.breakBackgroundImage,'/assets/nicole-away-v1.png');
 const personal={...store.getConfig(),waitingBackground:'video'};patch=packs.buildPatch(personal,{preset:'vesna',preserveMedia:true});assert.equal(patch.waitingBackground,undefined);
});
test('Mixed combinations persist, reapply scoped cosmetic fields and never capture account, result or text data',t=>{
 const store=createReplayStore(),file=path.join(temp(t),'combinations.json'),combos=createCombinationStore(file);store.configure({toonHandle:'5-S2-1-9',names:['PrivateName'],waitingTitle:'PrivateText',catView:'rear',gameFrameStyle:'nicole',waitingTheme:'nahida',breakTheme:'vesna'});store.add('win');const saved=combos.save('我的混搭',store.getConfig());assert.equal(saved.patch.gameFrameStyle,'nicole');assert.equal(saved.patch.waitingTheme,'nahida');assert.equal(saved.patch.breakTheme,'vesna');for(const forbidden of ['toonHandle','names','replayDirectory','waitingTitle','mmr','enabled','catX','catView'])assert.equal(Object.hasOwn(saved.patch,forbidden),false,forbidden);
 const restored=createCombinationStore(file);const patch=packs.buildPatch(store.getConfig(),{preset:saved.id,modules:['waiting','break']},restored.list());assert.equal(patch.waitingTheme,'nahida');assert.equal(patch.breakTheme,'vesna');assert.equal(patch.gameFrameStyle,undefined);store.configure(patch);assert.equal(store.snapshot().stats.wins,1);assert.equal(store.getConfig().toonHandle,'5-S2-1-9');
 assert.equal(combos.save('我的混搭',store.getConfig()).id,saved.id);assert.equal(combos.list().length,1);combos.remove(saved.id);assert.equal(combos.list().length,0);assert.throws(()=>combos.save('bad\nname',store.getConfig()));
});
test('Waiting daily selections default off, persist independently and render only own daily data including away mapping',()=>{
 const store=createReplayStore();for(const p of ['waiting','break'])for(const k of ['ShowZerglings','ShowZealots','ShowWorkersKilled','ShowStrongest','ShowDailyTime'])assert.equal(store.getConfig()[p+k],false);
 store.configure({waitingShowZealots:true,breakShowWorkersKilled:true});assert.equal(store.getConfig().breakShowZealots,false);assert.throws(()=>sanitize({waitingShowZealots:'true'}));
 const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:false,textContent:'',children:[],style:{setProperty(){}},parentElement:{},getAttribute(){return '';},append(...args){this.children.push(...args);},replaceChildren(){this.children=[];}});return nodes.get(id);};const win={SceneThemes:require('../public/scene-themes.js'),};
 const context=vm.createContext({window:win,document:{getElementById:node,createElement:()=>({children:[],append(...args){this.children.push(...args);}})}});for(const file of ['daily-model.js','ladder-overlay.js'])vm.runInContext(fs.readFileSync(require.resolve('../public/'+file),'utf8'),context);
 const ladder=store.snapshot();ladder.stats.daily={...ladder.stats.daily,zealots:24,workersKilled:15,replayCount:1,coverage:{zerglings:1,zealots:1,workersKilled:1}};win.LadderOverlay.render({scene:'intermission',ladder});assert.equal(node('waitingDailyMetrics').hidden,false);assert.equal(node('waitingDailyMetrics').children.length,1);assert.equal(node('waitingDailyMetrics').children[0].children[0].textContent,'今日刷叉');assert.match(node('waitingDailyMetrics').children[0].children[1].textContent,/24/);
 win.LadderOverlay.render({scene:'break',ladder});assert.equal(node('waitingDailyMetrics').children.length,1);assert.match(node('waitingDailyMetrics').children[0].children[1].textContent,/15/);win.LadderOverlay.render({scene:'game',ladder});assert.equal(node('ladderWaiting').hidden,true);
});
test('Combination save/apply API is authenticated, survives restart, and all scenes change without changing the live phase',async t=>{
 const dir=temp(t),app=createAssistant({port:0,dataDir:dir,sc2Reader:async()=> 'offline',intervalMs:60000});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const base='http://127.0.0.1:'+app.server.address().port,token=(await(await fetch(base)).text()).match(/name="control-token" content="([a-f\d]+)"/)[1];const act=async(body,auth=token)=>{const r=await fetch(base+'/api/action',{method:'POST',headers:{'X-Control-Token':auth},body:JSON.stringify(body)});return{code:r.status,state:await r.json()};};
 assert.equal((await act({action:'outfitSave',name:'mix'},'bad')).code,403);await act({action:'ladderConfigure',config:{gameFrameStyle:'nicole',waitingTheme:'nahida',breakTheme:'vesna'}});const saved=await act({action:'outfitSave',name:'mix'});assert.equal(saved.code,200);const combo=saved.state.outfit.combinations[0];await act({action:'outfitApply',choice:{preset:'starcraft'}});const applied=await act({action:'outfitApply',choice:{preset:combo.id}});assert.equal(applied.code,200);assert.equal(applied.state.scene,'intermission');assert.equal(applied.state.ladder.config.gameFrameStyle,'nicole');assert.equal(applied.state.ladder.config.waitingTheme,'nahida');assert.equal(applied.state.ladder.config.breakTheme,'vesna');assert.equal(createCombinationStore(path.join(dir,'outfit-combinations.json')).list().length,1);
 await act({action:'outfitUndo'});assert.equal(app.ladder.getConfig().waitingTheme,'starcraft');
});

test('Daily setup status chooses explicit ID, exact nickname or directory identity and prompts when missing',()=>{
 const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',checked:false,type:'text',dataset:{},contentWindow:{postMessage(){}},addEventListener(){},replaceChildren(){},append(){}});return nodes.get(id);},win={};const context=vm.createContext({window:win,location:{origin:'http://localhost'},document:{getElementById:node,querySelectorAll:()=>[],createElement:()=>({append(){}})}});for(const file of ['daily-model.js','daily-workspace.js'])vm.runInContext(fs.readFileSync(require.resolve('../public/'+file),'utf8'),context);
 const store=createReplayStore();const draw=()=>win.DailyWorkspace.render({ladder:store.snapshot()});draw();assert.match(node('dailyIdentityStatus').textContent,/尚未确认/);store.configure({replayDirectory:'C:\\Game\\5-S2-1-9\\Replays\\Multiplayer'});draw();assert.match(node('dailyIdentityStatus').textContent,/从录像目录识别账号：5-S2-1-9/);store.configure({names:['Me']});draw();assert.match(node('dailyIdentityStatus').textContent,/精确昵称.*Me/);store.configure({toonHandle:'5-S2-1-10'});draw();assert.match(node('dailyIdentityStatus').textContent,/账号ID：5-S2-1-10/);
});
