const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {createReplayStore}=require('../ladder-replays.cjs'),{createAssistant,sanitize}=require('../ladder-server.cjs'),{AutomationEngine}=require('../sc2.cjs'),{parseReplay}=require('../replay-watcher.cjs'),vm=require('node:vm');
const defaults=sanitize({});
const base=Date.parse('2026-10-06T15:59:00Z');
function replay(at,result='W',handle='5-S2-1-9') {const me={human:true,toonHandle:handle,name:'Me',race:'Terran',mmr:4000},op={human:true,toonHandle:'5-S2-1-10',name:'Opponent',race:'Zerg',mmr:4000};return{ok:true,at,durationSeconds:30,map:'Map',players:[me,op],selfPlayers:[me],opponents:[op],selfResult:result};}
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'直播场次-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return path.join(dir,'records.json');}
test('Session starts at launch, excludes earlier imports and copied replays, while daily history stays intact',()=>{
 let now=base;const store=createReplayStore(null,()=>now);store.configure({toonHandle:'5-S2-1-9'});store.acceptReplay(replay(base-30000),'old');assert.equal(store.snapshot().stats.wins,1);assert.equal(store.snapshot().session.stats.total,0);
 now+=10000;const p=replay(now);store.acceptReplay(p,'new');assert.equal(store.snapshot().session.startedAt,base);assert.equal(store.snapshot().session.stats.wins,1);assert.equal(store.snapshot().stats.wins,2);
 store.acceptReplay(p,'copied');assert.equal(store.snapshot().session.stats.total,1);assert.equal(store.snapshot().stats.total,2);
});
test('A stream crossing Beijing midnight keeps its session count; restarting resets only session scoring',t=>{
 let now=base;const file=temp(t),store=createReplayStore(file,()=>now);store.configure({toonHandle:'5-S2-1-9'});now+=10000;store.acceptReplay(replay(now),'before-midnight');now+=60000;const p=replay(now,'L');store.acceptReplay(p,'after-midnight');assert.equal(store.snapshot().date,'2026-10-07');assert.equal(store.snapshot().stats.total,1);assert.equal(store.snapshot().session.stats.total,2);assert.equal(store.snapshot().session.stats.losses,1);
 now+=10000;const restarted=createReplayStore(file,()=>now);assert.equal(restarted.snapshot().session.stats.total,0);assert.equal(restarted.snapshot().stats.total,1);restarted.acceptReplay(p,'copy-on-restart');assert.equal(restarted.snapshot().session.stats.total,0);now+=10000;restarted.acceptReplay(replay(now),'new-session');assert.equal(restarted.snapshot().session.stats.wins,1);assert.equal(restarted.snapshot().stats.total,2);
});
test('Session undo leaves pre-launch records alone, reconciles manual corrections and filters AI',()=>{
 let now=base;const store=createReplayStore(null,()=>now);store.configure({toonHandle:'5-S2-1-9'});store.acceptReplay(replay(base-180000),'old');store.undo('session');assert.equal(store.snapshot().stats.total,1);
 now+=10000;store.add('loss');store.acceptReplay(replay(now),'linked');assert.equal(store.snapshot().session.stats.total,1);assert.equal(store.snapshot().session.stats.losses,1);store.undo('session');assert.equal(store.snapshot().session.stats.total,0);assert.equal(store.snapshot().stats.total,1);
 const ai=replay(now);ai.players[1].human=false;assert.equal(store.acceptReplay(ai,'ai').kind,'skipped');assert.match(store.snapshot().status,/人机/);assert.equal(store.snapshot().stats.total,1);
 store.configure({toonHandle:'5-S2-1-11'});now+=10000;store.acceptReplay(replay(now,'W','5-S2-1-11'),'other-account');assert.equal(store.snapshot().session.stats.total,1);store.configure({toonHandle:'5-S2-1-9'});assert.equal(store.snapshot().session.stats.total,0);
});
test('Default zero delay confirms entry and covers menus immediately and supports decimal tuning',()=>{
 assert.equal(defaults.sc2StartDelay,0);assert.equal(defaults.sc2EndDelay,0);assert.equal(sanitize({sc2StartDelay:0.2,sc2EndDelay:0.4}).sc2EndDelay,0.4);for(const bad of [NaN,Infinity,-0.1,11,'0'])assert.throws(()=>sanitize({sc2StartDelay:bad}));
 const engine=new AutomationEngine(),config={...defaults,sc2AutoEnabled:true};assert.equal(engine.step('live',config,'intermission',false,0).target,null);assert.equal(engine.step('live',config,'intermission',false,250).target,'game');assert.equal(engine.step('menu',config,'game',false,500).target,'intermission');assert.equal(engine.step('menu',config,'game',false,750).target,'intermission');assert.equal(engine.step('offline',config,'game',false,1000).target,null);
 const delayed=new AutomationEngine(),slow={...config,sc2StartDelay:0.6};for(const time of [0,250,500])assert.equal(delayed.step('live',slow,'intermission',false,time).target,null);assert.equal(delayed.step('live',slow,'intermission',false,750).target,'game');
});
test('Live scoreboard and waiting use session results while today longest still uses daily history',()=>{
 const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',hidden:false,style:{setProperty(){}},parentElement:{},getAttribute(){return '';},dataset:{}});return nodes.get(id);};const win={};vm.runInNewContext(fs.readFileSync(require.resolve('../public/scoreboard.js'),'utf8'),{window:win,document:{getElementById:node,body:{dataset:{}}}});vm.runInNewContext(fs.readFileSync(require.resolve('../public/ladder-overlay.js'),'utf8'),{window:win,document:{getElementById:node}});
 let now=base;const store=createReplayStore(null,()=>now);store.configure({toonHandle:'5-S2-1-9',scoreboardEnabled:true,waitingShowLongest:true});store.acceptReplay(replay(base-20000),'old');now+=10000;store.acceptReplay(replay(now,'L'),'new');const state={scene:'intermission',ladder:store.snapshot()};win.ScoreboardOverlay.render(state,{standalone:true});win.LadderOverlay.render(state);assert.equal(node('scoreboardWins').textContent,0);assert.equal(node('scoreboardLosses').textContent,1);assert.equal(node('waitingRecord').textContent,'0 胜 1 负');assert.equal(node('waitingLongest').hidden,false);assert.equal(state.ladder.stats.wins,1);
});
test('API publishes a launch boundary, accepts decimal delays, and validates undo scope',async t=>{
 let now=base;const app=createAssistant({port:0,dataDir:null,now:()=>now,sc2Reader:async()=> 'offline',intervalMs:100000});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const origin='http://127.0.0.1:'+app.server.address().port,html=await(await fetch(origin)).text(),token=html.match(/name="control-token" content="([a-f\d]+)"/)[1];const action=async payload=>{const response=await fetch(origin+'/api/action',{method:'POST',headers:{'X-Control-Token':token},body:JSON.stringify(payload)});return{code:response.status,state:await response.json()};};
 assert.equal(app.snapshot().ladder.session.startedAt,base);assert.equal((await action({action:'configure',config:{sc2StartDelay:0.1,sc2EndDelay:0.2}})).code,200);assert.equal((await action({action:'ladderUndo',scope:'wrong'})).code,400);now+=10000;const recorded=await action({action:'ladderRecord',result:'win'});assert.equal(recorded.state.ladder.session.stats.wins,1);const undone=await action({action:'ladderUndo',scope:'session'});assert.equal(undone.state.ladder.session.stats.total,0);
});
