const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),zlib=require('node:zlib'),vm=require('node:vm');
const {createStylePackStore,png}=require('../style-packs.cjs'),{createAssistant}=require('../ladder-server.cjs'),outfits=require('../public/outfit-presets.js'),{defaults,sanitize}=require('../ladder-replays.cjs');
const example=JSON.parse(fs.readFileSync(path.join(__dirname,'../public/style-pack-example.json'),'utf8'));
const table=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});const crc=b=>{let c=0xffffffff;for(const x of b)c=table[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0;};
function chunk(type,data){const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,8+data.length)),8+data.length);return b;}
function image(w,h,pixel=()=>[0,0,0,0]){const head=Buffer.alloc(13);head.writeUInt32BE(w);head.writeUInt32BE(h,4);head[8]=8;head[9]=6;const raw=Buffer.alloc((w*4+1)*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const p=pixel(x,y);for(let i=0;i<4;i++)raw[y*(w*4+1)+1+x*4+i]=p[i];}return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',head),chunk('IDAT',zlib.deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]);}
const encoded=b=>'data:image/png;base64,'+b.toString('base64');
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'style-pack-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
const request=p=>(async function*(){yield Buffer.from(JSON.stringify(p));})();
test('style library installs without applying, exports a self-contained file, survives restart and preserves installed assets after removal',async t=>{
 const dir=temp(t),s=createStylePackStore(dir),sprite=image(1536,512,(x,y)=>x%512>100&&x%512<400&&y>50&&y<440?[145,200,150,255]:[0,0,0,0]);const frame=image(1920,1080,(x,y)=>y>1065?[150,200,170,255]:[0,0,0,0]);
 const p={...example,assets:{assistantRear:encoded(sprite),frame:encoded(frame)}};const installed=await s.install(request(p));assert.equal(installed.frame,'custom');assert.equal(installed.cat,'custom');assert.match(installed.assets.frame,/^\/style-assets\/[a-f\d]{64}\.png$/);assert.equal(s.list().length,1);assert.deepEqual(s.exportPack(installed.id),p);
 const reopened=createStylePackStore(dir);assert.deepEqual(reopened.list(),s.list());await assert.rejects(reopened.install(request(p)),/同ID/);const file=reopened.assetFile(installed.assets.frame);reopened.remove(installed.id);assert.equal(reopened.list().length,0);assert.ok(fs.existsSync(file));
});
test('invalid assets, active content, foreign paths and unsupported dimensions leave the library untouched',async t=>{
 const dir=temp(t),s=createStylePackStore(dir);const invalid=[{...example,id:'../../escape'},{...example,script:'alert(1)'},{...example,assets:{frame:'https://example.com/a.png'}},{...example,assets:{frame:encoded(image(1920,1080,()=>[0,0,0,255]))}},{...example,assets:{assistantFront:encoded(image(512,512))}},{...example,assets:{waiting:encoded(image(100,100))}},{...example,assets:{unknown:encoded(image(1,1))}}];
 for(const input of invalid)await assert.rejects(s.install(request(input)));assert.deepEqual(s.list(),[]);assert.equal(fs.existsSync(path.join(dir,'style-packs','index.json')),false);
 const broken=image(1536,512);broken[42]^=1;assert.throws(()=>png(broken,'assistantFront'),/校验/);await assert.rejects(s.install((async function*(){yield Buffer.alloc(33*1024*1024);})()),/32MB/);
});
test('custom outfits preserve account, results, positions, views and uploaded media while applying validated frame, sprites and scenes',async t=>{
 const s=createStylePackStore(temp(t)),sprite=image(1536,512),scene=image(1920,1080,()=>[10,30,40,255]);const p=await s.install(request({...example,assets:{assistantFront:encoded(sprite),waiting:encoded(scene),away:encoded(scene)}}));
 const c={...defaults,names:['Me'],toonHandle:'5-S2-1-12',mmr:5100,catX:80,catView:'rear',waitingBackground:'video',waitingBackgroundVideo:'/scene-media/'+'a'.repeat(64)+'.mp4'};
 const patch=outfits.buildPatch(c,{preset:p.id,preserveMedia:true},s.list());assert.equal(patch.waitingBackground,undefined);assert.equal(patch.catRearImage,p.assets.assistantFront);assert.equal(patch.breakBackground,'image');assert.equal(patch.breakTheme,'custom');const applied=sanitize(patch,c);for(const k of ['names','toonHandle','mmr','catX','catView','waitingBackgroundVideo'])assert.deepEqual(applied[k],c[k]);
 const replaced=outfits.buildPatch(c,{preset:p.id,modules:['waiting'],preserveMedia:false},s.list());assert.equal(replaced.waitingTheme,'custom');assert.equal(replaced.waitingBackgroundImage,p.assets.waiting);assert.equal(replaced.waitingTextColor,example.palette.text);assert.equal(replaced.catCharacter,undefined);assert.throws(()=>sanitize({gameFrameImage:'file:///c:/secret'}));
});
test('style install/export/remove require local authorization; installation never changes live configuration and scoped apply/undo survives custom image export',async t=>{
 const dir=temp(t),app=createAssistant({port:0,dataDir:dir,sc2Reader:async()=>{throw Error('offline');},intervalMs:60000});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const base='http://127.0.0.1:'+app.server.address().port,html=await(await fetch(base)).text(),token=html.match(/name="control-token" content="([^"]+)"/)[1];
 const input={...example,assets:{frame:encoded(image(1920,1080))}},headers={'Content-Type':'application/json','X-Control-Token':token,Origin:base};const upload=extra=>fetch(base+'/api/style-pack-install',{method:'POST',headers:{...headers,...extra},body:JSON.stringify(input)});
 const before=app.ladder.snapshot();assert.equal((await upload({'X-Control-Token':'bad'})).status,403);assert.equal((await upload({Origin:'https://example.com'})).status,403);const response=await upload({});assert.equal(response.status,200);const result=await response.json();assert.deepEqual(app.ladder.snapshot(),before);assert.equal(result.state.stylePacks.length,1);
 const action=body=>fetch(base+'/api/action',{method:'POST',headers,body:JSON.stringify(body)});assert.equal((await action({action:'outfitApply',choice:{preset:result.pack.id,modules:['gameframe','scoreboard']}})).status,200);assert.equal(app.ladder.getConfig().gameFrameStyle,'custom');assert.match(await(await fetch(base+'/gameframe.svg')).text(),/data:image\/png;base64,/);
 assert.equal((await fetch(base+'/api/style-pack-export?id='+result.pack.id)).status,403);const exported=await fetch(base+'/api/style-pack-export?id='+result.pack.id,{headers});assert.deepEqual(await exported.json(),input);assert.equal((await fetch(base+result.pack.assets.frame)).status,200);assert.equal((await action({action:'outfitUndo'})).status,200);assert.deepEqual(app.ladder.getConfig(),before.config);
 assert.equal((await action({action:'stylePackRemove',id:result.pack.id})).status,200);assert.equal((await(await fetch(base+'/api/state')).json()).stylePacks.length,0);for(const route of ['/style-pack-workspace.js','/style-pack.css','/style-pack-prompt.txt','/style-pack-example.json'])assert.equal((await fetch(base+route)).status,200);
});
test('custom sprite markup keeps exactly one rendered half keyboard, preserves three poses and escapes frame asset references',()=>{
 const model=require('../public/cat-keyboard-template.js');const markup=model.build({catCharacter:'custom',catView:'rear'});assert.match(markup,/cat-character-custom/);assert.equal((markup.match(/class="cat-board"/g)||[]).length,1);const css=fs.readFileSync(path.join(__dirname,'../public/cat-keyboard.css'),'utf8');assert.match(css,/cat-character-custom.*background-size:300% 100%/);const frame=require('../public/gameframe-template.js').build({gameFrameStyle:'custom',gameFrameImage:'/style-assets/'+'a'.repeat(64)+'.png'});assert.match(frame,/data-frame-theme="custom"/);assert.match(frame,/width="1920" height="1080"/);
 const html=fs.readFileSync(path.join(__dirname,'../public/ladder.html'),'utf8');assert.match(html,/id="stylePackBuildInstall"/);assert.equal((html.match(/id="stylePackFile"/g)||[]).length,1);
});
