const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawnSync}=require('node:child_process');
const {createReplayStore}=require('../ladder-replays.cjs'),{createReplayWatcher}=require('../replay-watcher.cjs');
test('new tracker protocol preserves exact decoding, limits fallback and decodes official public fixture',()=>{const r=spawnSync(require('../runtime-paths.cjs').python(),['-X','utf8',path.join(__dirname,'tracker-version-test.py')],{encoding:'utf8',windowsHide:true});assert.equal(r.status,0,r.stdout+r.stderr);assert.match(r.stderr,/Ran 4 tests/);});
test('automatic polling fills previously unavailable unit metrics without manual scanning, extra results or display requirement',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tracker-version-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const at=Date.parse('2026-10-09T01:00:00Z');let clock=at-10000;const store=createReplayStore(null,()=>clock);clock=at+10000;store.configure({toonHandle:'5-S2-1-1',replayDirectory:dir,enabled:true,autoTrack:true,dailyEnabled:false});
 const me={toonHandle:'5-S2-1-1',name:'Me',human:true,race:'Protoss',mmr:4000},op={toonHandle:'5-S2-1-2',name:'Other',human:true,race:'Zerg',mmr:4000},parsed={ok:true,at,map:'Map',durationSeconds:600,players:[me,op],selfPlayers:[me],opponents:[op],selfResult:'W',dailyMetrics:{version:1,zerglings:null,zealots:null,workersKilled:null,status:'unavailable',note:'暂不支持版本 98370 的单位跟踪统计'}};
 store.acceptReplay(parsed,'old');const before=store.snapshot();assert.equal(before.stats.daily.zealots,null);const file=path.join(dir,'new.SC2Replay');fs.writeFileSync(file,'fixture');fs.utimesSync(file,new Date(at-5000),new Date(at-5000));
 const watcher=createReplayWatcher({store,now:()=>clock,intervalMs:10,parser:async()=>({...parsed,dailyMetrics:{version:1,zerglings:0,zealots:14,workersKilled:22,status:'ready',note:''}})});t.after(()=>watcher.close());
 const deadline=Date.now()+1500;while(store.snapshot().stats.daily.zealots===null&&Date.now()<deadline)await new Promise(r=>setTimeout(r,10));const after=store.snapshot();assert.equal(after.stats.daily.zealots,14);assert.equal(after.stats.daily.workersKilled,22);assert.equal(after.stats.daily.coverage.zealots,1);assert.equal(after.stats.total,before.stats.total);assert.equal(after.session.stats.total,before.session.stats.total);assert.equal(after.session.startedAt,before.session.startedAt);assert.equal(after.records[0].id,before.records[0].id);assert.equal(after.config.dailyEnabled,false);
});
