const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {createReplayStore,sanitize}=require('../ladder-replays.cjs');
test('scoreboard is optional and its configuration survives restart without losing recorded results',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ladder-tools-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'data.json'),now=()=>Date.parse('2026-10-05T08:00:00Z'),s=createReplayStore(file,now);s.configure({names:['Me']});s.add('win');s.updateMMR(4000);s.configure({scoreboardEnabled:false,scoreboardTemplate:'bluegold',scoreboardX:123,scoreboardY:234,showHUD:true});const restored=createReplayStore(file,now);assert.equal(restored.snapshot().stats.wins,1);assert.equal(restored.getConfig().mmr,4000);assert.equal(restored.getConfig().showHUD,true);assert.equal(restored.getConfig().scoreboardEnabled,false);assert.equal(restored.getConfig().scoreboardTemplate,'bluegold');assert.equal(restored.getConfig().scoreboardX,123);restored.configure({scoreboardEnabled:true});assert.equal(restored.snapshot().stats.total,1);});
test('module settings reject malformed switches, unsafe template names and positions',()=>{for(const input of [{scoreboardEnabled:'false'},{scoreboardDetails:1},{scoreboardTemplate:'<script>'},{scoreboardX:-1},{scoreboardY:1081},{scoreboardWidth:9999},{scoreboardScale:151}])assert.throws(()=>sanitize(input));});
test('information templates hide in game and return between matches without affecting the scoreboard',()=>{
  const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:true,textContent:'',className:'',style:{setProperty(){}},parentElement:{hidden:false},getAttribute(){return '';}});return nodes.get(id);},win={};
  const document={getElementById:node,body:{dataset:{}}};
  for(const file of ['ladder-overlay.js','scoreboard.js'])vm.runInNewContext(fs.readFileSync(require.resolve('../public/'+file),'utf8'),{window:win,document});
  const state={scene:'game',ladder:createReplayStore().snapshot()};
  for(const template of ['compact','bluegold','dual','custom']){
    state.ladder.config.template=template;
    for(const scene of ['game','intermission','game','break']){
      state.scene=scene;win.LadderOverlay.render(state);win.ScoreboardOverlay.render(state);
      assert.equal(node('ladderHUD').hidden,scene!=='intermission',template+' / '+scene);
      assert.equal(node('scoreboardWidget').hidden,scene!=='game');
    }
  }
  state.scene='intermission';state.ladder.config.showHUD=false;win.LadderOverlay.render(state);assert.equal(node('ladderHUD').hidden,true);
  state.ladder.config.showHUD=true;state.ladder.config.enabled=false;win.LadderOverlay.render(state);assert.equal(node('ladderHUD').hidden,true);
  state.ladder.config.enabled=true;delete state.ladder.config.scoreboardEnabled;state.scene='game';win.LadderOverlay.render(state);assert.equal(node('ladderHUD').hidden,false,'legacy rendering remains compatible');
  const html=fs.readFileSync(require.resolve('../public/ladder.html'),'utf8');assert.match(html,/data-src="\/output\?preview=1&phase=intermission&module=overlay"/);
});
test('combined output can show the scoreboard with the information bar disabled and hide it on exit',()=>{const nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:true,textContent:'',style:{setProperty(){}},className:''});return nodes.get(id);};const win={};vm.runInNewContext(fs.readFileSync(require.resolve('../public/scoreboard.js'),'utf8'),{window:win,document:{getElementById:node,body:{dataset:{}}}});const store=createReplayStore(),state={scene:'game',ladder:store.snapshot()};state.ladder.config.showHUD=false;win.ScoreboardOverlay.render(state);assert.equal(node('scoreboardWidget').hidden,false);assert.equal(node('scoreboardWins').textContent,0);state.ladder.config.scoreboardEnabled=false;win.ScoreboardOverlay.render(state);assert.equal(node('scoreboardWidget').hidden,true);win.ScoreboardOverlay.render(state,{preview:true});assert.equal(node('scoreboardWidget').hidden,false);state.ladder.config.scoreboardEnabled=true;state.scene='intermission';win.ScoreboardOverlay.render(state);assert.equal(node('scoreboardWidget').hidden,true);win.ScoreboardOverlay.render(state,{standalone:true});assert.equal(node('scoreboardWidget').hidden,false);});
test('workspace panels contain unique controls and the live preview is initially visible',()=>{const html=fs.readFileSync(require.resolve('../public/ladder.html'),'utf8'),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,'Duplicate controls');for(const view of ['tools','scoreboard','overlay','settings'])assert.match(html,new RegExp(`data-view="${view}"[^>]+hidden`));assert.match(html,/data-view="console" class="workspace-view">/);assert.match(html,/id="homeScoreboard"/);assert.match(html,/id="scoreboardEnabled"/);assert.match(html,/\/workspace.js/);});
